### ISSUE TITLE
Performance problems when saving multiple documents

### ISSUE THREAD

**Issue by MaikelH** [typeorm/typeorm#1115]
### Problem
In our system we noticed slowdowns when we needed to insert a lot entities (up to 10.000). To see what the exact problem was we created a test script to test the insert speed of TypeORM. 

For the test we used the `save()` method inside a transaction ([see here](https://github.com/MaikelH/db-access-perf-tests/blob/master/src/tests/TypeormTest.ts)). In the screenshot below we can see the results of the test we ran with different number of documents.

![chart 1](https://user-images.githubusercontent.com/2207042/32171367-2ada6c88-bd78-11e7-995b-c3134cb8af39.png)

We compare against raw queries using `pg-promise`. The expected behavior is that TypeORM is slower than `pg-promise`, but should still scale linear. What can be seen in the graph is that TypeORM exhibits `O(n^2)` runtime complexity instead. Inserting 16000 documents takes about 7.5 minutes using TypeORM. 

The table below gives a more detailed view (times are in milliseconds), all the numbers are the average of 10 runs.

Documents | PG-Batch | TypeORM | PG-Promise | PG-InsertHelper
-- | -- | -- | -- | --
500 | 179 | 824 | 250 | 54
1000 | 268 | 1931 | 469 | 93
2000 | 476 | 12602 | 993 | 130
4000 | 863.1 | 58696 | 2015.7 | 216.5
8000 | 1618.9 | 116990.8 | 3886.1 | 385.9
16000 | 3281.2 | 438171.8 | 7706.2 | 736.8

What can be seen in the table is that when inserting a smaller amount of documents the performance is fine. 

After every test run the NodeJS process was restarted. If we do all the test runs in the same process (loop) the test results are slightly better on average but the `O(n^2)` runtime complexity is still there. See the google doc sheet `Machine 2 (continuous)` for the results.

### Solution
Currently not known.

### Environment
TypeORM: 0.1.1
Database: Postgres 9.6
Node: 6.11
OS: Ubuntu

Entity used:

```typescript
@Entity()
export class Document {
	@PrimaryColumn('text')
	id: string;

	@Column('text')
	docId: string;

	@Column('text')
	label: string;

	@Column('text')
	context: string;

	@Column({type: 'jsonb'})
	distributions: Distribution[];

	@Column({type: 'timestamp with time zone'})
	date: Date;
}

export interface Distribution {
	weight: string,
	id: number,
	docId: number
}
```

### More information
- [Github repository with test code](https://github.com/MaikelH/db-access-perf-tests/)
- [Google Spreadsheet with results](https://docs.google.com/spreadsheets/d/1Ra43WFRzxJffyQww_SYW5dgmL_hc9HGtpI7G0SrCUsA/edit?usp=sharing)

**Comment by pleerock** [comment]
Thank you very much for your investigation and detailed information you provided. Currently Im working on refactoring of persistence mechanizm we have and lot of improvements are coming in `0.2.0`. Im planning to finish it this week or early next week and publish a first 0.2.0.alpha version with those changes. This will be a starting point of performance improvements and I'll try to make `save` method performance as good as possible. If you help me to test new versions and continue provide a feedback I'll try to justify performance as much as possible.

**Comment by jondediego** [comment]
Do you know if this performance improvements will also affect cordova drivers? We are looking forward to trying those changes.
#1109

**Comment by MaikelH** [comment]
@pleerock Ok good to hear. I will definitely will test the new version of TypeORM and see how it performs. I am interested to see how it will perform. 

@jondediego My suspicion is that the performance problems are in the persistence layer and not in the drivers themselves, which would mean that the changes should affect all drivers.

**Comment by vitaly-t** [comment]
@MaikelH I am the author of `pg-promise`, and just wanted to mention that you performance results against `pg-promise` are far from what you get when you do it right. I have just submitted a [PR](https://github.com/MaikelH/db-access-perf-tests/pull/3) to show you how you should do it to get really good performance.

**Comment by vitaly-t** [comment]
@MaikelH Results in **PG-Batch** are deceiving, as you are using the method there that should never be used in practice, as it depletes the connection pool (hence the temporary performance advantage), and offers no data integrity. I would suggest to throw that approach/example away.

**Comment by MaikelH** [comment]
@vitaly-t Why does it actually depletes the connection pool? I assumed by using the `batch` function, it would only do one request to the postgres. But it still does multiple?

**Comment by vitaly-t** [comment]
@MaikelH I was referring to the `PG-Batch` example, the one that uses `db` directly and then uses `Promise.all`, not the one with the `t.batch` :) When you do it like that, you force all available connections out of the pool, so none will be available to do anything in parallel, until the operation is over.

**Comment by MaikelH** [comment]
Ah ok, I was a little bit confused. What you saying was the same thing I was thinking. My plan is to leave that example in just to show how not to do it. I added extra comments in the code that describe that that test is not production ready code and is there only as an example how not to do it.

**Comment by pleerock** [comment]
@MaikelH can you please re-run your tests against typeorm@0.2.0-alpha.1 (`npm i typeorm@next`)? Also you can skip transaction creation since `save` already does it for you.

Also can you please create another split typeorm category into "typeorm-save" and "typeorm-insert" ? Insertion is a more efficient alternative to `save` but with fewer sugar features provided by `save` method. Example:

```ts
return db.then((con: Connection) => {
    let start = new Date().getTime();
    const us = new UsageStats();
    us.start();
    
    return con.createQueryBuilder()
        .insert()
        .into(Document)
        .values(docs)
        // .useTransaction(true) // completely optional since now you must have only one insertion query with bulk insertion
        .execute()
        .then(doc => {
            let end = new Date().getTime();
            const stats = us.stop();

            console.log("[Typeorm] Call to persist took " + (end - start) + " milliseconds.");
            // console.log(`
            // avg cpu: ${stats.avgCpu}
            // avg memory: ${stats.avgMemory}
            // `)
        })
        .then(() => {
            return con.close();
        });
});
```

**Comment by MaikelH** [comment]
Nice, I will rerun the performance tests in the next couple of days and will post the outcomes. I expect to have the results the beginning of next week.

**Comment by MaikelH** [comment]
Ok I upgraded to `alpha.2`, which seems to fix the issue in #1191. I will rerun the tests in against `alpha.2`.

**Comment by pleerock** [comment]
I made even more fixes in `0.2.0-alpha.5` and here are results for 10.000 documents insertion:

```
### Run 1
[PG-Batch] Call to persist took 4196 milliseconds.
[TypeormInsert] Call to persist took 728 milliseconds.
[TypeormSave] Call to persist took 12290 milliseconds.
[PG-InsertHelper] Call to persist took 1796 milliseconds.
Finished test.
```

**Comment by MaikelH** [comment]
Ok that is looking good. I just run the tests against the `0.2.0-alpha.2` build. After that I will run them against the `0.2.0-alpha.5` build.

**Comment by pleerock** [comment]
In `0.2.0-alpha.6` I improved `save` method as well. There are new tests results:

```
### Run 1
[PG-Batch] Call to persist took 4036 milliseconds.
[TypeormInsert] Call to persist took 754 milliseconds.
[TypeormSave] Call to persist took 1192 milliseconds.
[PG-InsertHelper] Call to persist took 586 milliseconds.
Finished test.
```

I think now performance issues can rest in peace =)

**Comment by pleerock** [comment]
In `0.2.0-alpha.10` I added `{ chunk }` option which allow to make huge insertions possible in chunks:

```ts
        const posts: Post[] = [];
        for (let i = 0; i < 100000; i++) {
            const post = new Post();
            post.title = "Title " + i;
            post.description = "Hello" + i;
            posts.push(post);
        }
        await connection.manager.save(posts, { chunk: 10000 });
```

Following will generate 10 queries each inserts 10.000 posts.

This is needed because all drivers have their own limitations on number of parameters they can contain in query.

I also optimized `save` method and here are new test results:

```
### Run 1
[PG-Batch] Call to persist took 5204 milliseconds.
[TypeormInsert] Call to persist took 653 milliseconds.
[TypeormSave] Call to persist took 776 milliseconds.
[PG-InsertHelper] Call to persist took 715 milliseconds.
Finished test.
```

**Comment by icepeng** [comment]
I faced this problem today. When updating relations of a large number of rows, performance was significantly degraded.

The performance improvement of 0.2.0-alpha is encouraging. However, we are not able to use it until 0.2.0 is officially released. Are there any alternatives to improve performance right now?

**Comment by pleerock** [comment]
no you can't. Use alpha version there is nothing wrong with it.

**Comment by pleerock** [comment]
I'll close this issue since it is resolved. @MaikelH thanks for the report, thanks to it we solved those issues. Let me know once you test latest.

**Comment by Alex0007** [comment]
Is this resolved? Just tested typeorm@next and adding `chunk` option makes no difference

```
    await getRepository(Address).save(addresses as Address[], {chunk: 50000})
```

**Comment by JesperBalslev** [comment]
> In `0.2.0-alpha.10` I added `{ chunk }` option which allow to make huge insertions possible in chunks:
> 
> ```ts
>         const posts: Post[] = [];
>         for (let i = 0; i < 100000; i++) {
>             const post = new Post();
>             post.title = "Title " + i;
>             post.description = "Hello" + i;
>             posts.push(post);
>         }
>         await connection.manager.save(posts, { chunk: 10000 });
> ```
> 
> Following will generate 10 queries each inserts 10.000 posts.
> 
> This is needed because all drivers have their own limitations on number of parameters they can contain in query.
> 
> I also optimized `save` method and here are new test results:
> 
> ```
> ### Run 1
> [PG-Batch] Call to persist took 5204 milliseconds.
> [TypeormInsert] Call to persist took 653 milliseconds.
> [TypeormSave] Call to persist took 776 milliseconds.
> [PG-InsertHelper] Call to persist took 715 milliseconds.
> Finished test.
> ```

Hello pleerock, love typeOrm. We are however confused on how chunk actually works. How can we check if it does anything at all? When looking at the server, it is always 1 transaction with several inserts, no matter what we do.

Also, is chunk supposed to be the chunk SIZE or the chunk AMOUNT? In your example here it seems to be 10000 which turns into 10 chunks, but when checking the description in the code, it says:

`Breaks save execution into given number of chunks. For example, if you want to save 100.000 objects but you have issues with saving them, you can break them into 10 groups of 10.000 objects (by setting { chunk: 10 }) and save each group separately. This option is needed to perform very big insertions when you have issues with underlying driver parameter number limitation.`

Thanks in advance!

**Comment by JesperBalslev** [comment]
> _UPD_.: using `insert` instead of `save` fixed my problem

Using insert worked for me also. But the issue with the chunk description is still confusing.

**Comment by 11TStudio** [comment]
Sharing this here as it might maybe help someone who still gets low execution times;
**Our solution was;**
Manually chunk our entities using the chunk method from lodash instead of the inbuild typeorm chunk option. (*250 items per chunk delivered the fastest execution time for our use case*) 
After this we saved them in a loop using the typeorm's .insert() method instead of .save() as it was faster. 
Basic structure example;
```
const customers = await getRepository(Customer).find({});
const cosaArray = customers.map((customer) => CustomerOwnSupplierAccess.Create(supplier, customer));
const chunked = chunk(cosaArray, 250);

await Promise.all(
  chunked.map(async (chunkedCosaArray) => {
    await getRepository(CustomerOwnSupplierAccess).insert(chunkedCosaArray);
  }),
);
```

Added this table to show the execution times we got each time with each different approach.
| Type of approach  | Execution time |
| ------------- | ------------- |
| .save() without any chunks inside a transaction  | ~5 minutes  |
| .save() without any chunks without transaction  | ~3.5 minutes  |
| .save() with typeorm chunk option (we did try all kind of amounts here; min 50 to max 1000) without transaction  | ~2.5 minutes  |
| .insert() with typeorm chunk option (we did try all kind of amounts here; min 50 to max 1000) without transaction  | ~1.5 minutes  |
| .save() with lodash chunk of entities (250 items) to save without trsansaction  | ~35 seconds  |
| .insert() with lodash chunk of entities (250 items) before we save without transaction  | ~25 seconds |
