### ISSUE TITLE
Cannot save cascade with postgres SQL

### ISSUE THREAD

**Issue by TovarishN** [typeorm/typeorm#125]
I have these kind of entities:

```
@Table()
export class Team {
	@PrimaryColumn("int") id: number;
	@Column() name: string;
	@Column() uniqueid: number;

	@ManyToOne(type => DataProvider, { cascadeInsert: true })
	@JoinColumn()
	provider: DataProvider;
}

@Table()
export class DataProvider {
	@PrimaryColumn("int") id: number;
	@Column() name: string;
	@Column() prefix: string;
}

const provider : DataProvider = {
    id: 5,
    name: "Example Name",
    prefix: "coing"
};

const awayTeam: Team = {
    id: 10,
    name: "Liverpool",
    uniqueid: 556,
    provider: provider
};
```

trying to save this with
`await this.conn.entityManager.persist(awayTeam);`
gives 

executing query: START TRANSACTION
executing query: INSERT INTO "team"("id", "name", "uniqueid", "provider") VALUES ($1,$2,$3,$4)  -- PARAMETERS: [10,"Liverpool",556,5]
executing query: INSERT INTO "data_provider"("id", "name", "prefix") VALUES ($1,$2,$3)  -- PARAMETERS: [5,"Example Name","coing"]
query failed: INSERT INTO "team"("id", "name", "uniqueid", "provider") VALUES ($1,$2,$3,$4)  -- PARAMETERS: [10,"Liverpool",556,5]
executing query: ROLLBACK
query failed: INSERT INTO "data_provider"("id", "name", "prefix") VALUES ($1,$2,$3)  -- PARAMETERS: [5,"Example Name","coing"]
(node:2168) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): error: insert or update on table "team" violates foreign key constraint "fk_b9baad251acb0297c357642a529"

**Comment by TovarishN** [comment]
Looks like insert query execution order is incorrect - first it has to insert  provider entity

**Comment by pleerock** [comment]
right, insert order is not correct. Im aware of this issue. TBH its pretty hard to determine a correct order of inserting object, because of complex cases when objects has recursive dependencies. If you use generated columns, you'll not have this issue. I'll work on this issue, until that please persist objects manually without cascade inserting in a correct order.

**Comment by TovarishN** [comment]
Cool! Thanks! Autogenerated primary id will do the job for me

**Comment by dcworldwide** [comment]
Experiencing the same issue. I'm also in a scenario where I need to set PKs explicitly.

**Comment by pleerock** [comment]
@dcworldwide yeah we need algorithm that will order entities in a right way. Its a complex task, not just to order from parent to child or versa. There can be more complex cases like:

post.category (nullable: false)
category.photo (nullable: true)
photo.post (nullable: false)

In this case category needs to be saved first, then post, then photo, after all photo needs to be updated in the category.

There are even more complex examples with more complex relations that needs to be covered.

cascades and non nullable columns bring a huge mess to this algorithm. I need some help there from those who are able to solve all these algorithmic problems. If you have experience in this area help will be appreciated.

**Comment by dcworldwide** [comment]
Which class in the codebase should the logic go?

**Comment by dcworldwide** [comment]
Off the top of my head, from a high level we might be able to use a [topological sort](https://en.wikipedia.org/wiki/Topological_sorting). As a pre-requisite step though, we'd need to ensure that the table graph is acyclic, so to do that, we could use a [spanning tree algorithm](https://www.tutorialspoint.com/data_structures_algorithms/spanning_tree.htm) to create a directed, acyclic graph which would be easy for the topo sort to traverse.

**Comment by pleerock** [comment]
> we'd need to ensure that the table graph is acyclic

yes, I made such check [here](https://github.com/typeorm/typeorm/blob/fc37ca1262e6bc22c9e55083330af43360f9f9ed/src/metadata-builder/EntityMetadataValidator.ts#L131)

> The performance penalty of the algorithms shouldn't be an issue given we'd only need to run them once on startup as we have all the neccessary info in reflect metadata.

sounds good.

> Which class in the codebase should the logic go?

Don't know yet, maybe better into separate class. Need to take a look on implementation before final decision can be done. [Here](https://github.com/pleerock/typeorm/blob/13ff9f44b8043774638c993cb62eb919559fa072/src/persistence/SubjectOperationExecutor.ts#L150-L150) I implemented temporary algorithm how entities are persisted.

**Comment by edskeizer** [comment]
I still have this bug with PostgreSQL even when I use autogenerated primary ids (classnames are mimicked):

```typescript
@Entity("events")
export class Event {

    @PrimaryColumn("int", { generated: true })
    id: number;

    /* Other columns here */

    @OneToMany(type => Value, value =>  value.event, {
        cascadeUpdate: true,
    })
    values: Value[] = [];
}
```
and
```typescript
@Entity("values")
export class Value {

    @PrimaryColumn("int", { generated: true })
    id: number;

    /* Other columns here */

    @ManyToOne(type => Event, event => event.values, {
        cascadeInsert: true,
        cascadeUpdate: true,
        cascadeRemove: false
    })
    @JoinColumn() // I tried without this line as well...
    event: Event;
}
```

When I run this code:
```typescript

let event: Event = new Event();
let value: Value = new Value();
// set some extra fields here
value.event = event; // I tried without this line as well...
event.values.push(value);

let eventRepository: Repository<Event> = getConnectionManager().get().getRepository(Event);
await eventRepository.persist(event);
```

The `event` object is saved to the database, but the `value` object is not.

**Comment by pleerock** [comment]
I suggest simply persist/update your entities without using cascades in the places where it does not work for you until this fix

**Comment by Deilan** [comment]
@pleerock Thanks for your explanation.

Persisting a graph in a db is a highly requested featured indeed. Looking forward to it.

**Comment by Deilan** [comment]
@pleerock Thanks for your explanation.

Persisting a graph in a db is a highly requested featured indeed. Looking forward to it.

Did I understand correctly that if there's a graph of fresh (not yet persisted, and PK's are `undefined` yet) parent entity and a collection of child entities, and there are relations decorators on both sides, typeorm should persist them just fine?

**Comment by Urigo** [comment]
@pleerock or anyone else,  could you provide an example with a workaround for postgres?
For some reasons even when I manually persist it still doesn't work for me currently

**Comment by pleerock** [comment]
@Urigo no no manual persist must work. Can you please provide a small code snippet what you are trying to do?

**Comment by Urigo** [comment]
@pleerock I think I found how to do that, I guess the problem is what I described here: https://github.com/typeorm/typeorm/issues/302#issuecomment-321658024

**Comment by pleerock** [comment]
I have completely refactored persistence system and implemented topological sorting for cascade persisted entities. This is issue must be resolved now. I release 0.2.0-alpha version with those changes. You can try it via `npm i typeorm@next`

**Comment by hwaterke** [comment]
@pleerock Amazing. I had problems with cascade behaviours (multiple levels of cascade inserts) and 0.2.0-alpha fixed the issue.
