### ISSUE TITLE
may i know is the feature to convert date to UTC before saving to mysql is removed since 0.1.18. It was working fine in 0.1.17. I tried all subsequent version from 0.1.18 onward and none of it is working.

### ISSUE THREAD

**Issue by cometta** [typeorm/typeorm#1999]
may i know is the feature to convert date to UTC before saving to mysql is removed since 0.1.18. It was working fine in 0.1.17. I tried all subsequent version from 0.1.18 onward and none of it is working.

**Issue type:**

[✔] question
[ ✔] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[✔ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ✔] `0.1.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

link to reference issue #976

**Comment by pleerock** [comment]
dates behaviour was changed (actually it was fixed). See #1717 and all related links for more information.

**Comment by cometta** [comment]
@pleerock, I read #1717, so for subsequent version, need to manually set server time to UTC so that typeorm save in UTC?

**Comment by chriskalmar** [comment]
@cometta, there is no reason for you to change your server time zone to UTC. The purpose of #1717 is actually to prevent this workaround. 
If you look at the original issue #1716 you will understand the benefits of the change.

You should be able to have the database server set to a different timezone than the application server (e.g. multi-datacenter architectures) and still be able to store the correct time. 
The only way to make this work is if every component (database, app server, client) sticks to dates/timestamps with timezone offset information.

Let's assume your user (client) is living in the timezone `+8` and your servers are in the timezone `+2`:
You don't want to calculated for each client living in another timezone the correct offset. You just send the date/timestamp including the timezone offset (in this example `+8`) to typeorm and it will be persisted correctly in the database (regardless it's timezone).
When you read out the date/timestamp and push it to the client, it will include the timezone offset as well, thus making it easy to convert it into the client's local time.

In any other scenario you would be forced to set the server time to UTC and to convert your client's timestamps into UTC first before persisting them. 

I hope this clarifies it for you.

**Comment by cometta** [comment]
example database server timezone +8 and date is saved as UTC.
on version 0.1.17, it return 2018-01-31T16:00:00.000Z .   (save as 2018-02-01 timezone+8) 
but on version 0.1.19 (tested), it return 2018-01-31T08:00:00.000Z   . Can Typeorm returns UTC time and independent of database server timezone?

**Comment by chriskalmar** [comment]
@cometta looks like the date got stored correctly.
I ran an example model on mysql and postgres to reproduce the problem but regardless of which timezone I move the servers to I still get the expected result `2018-01-31T16:00:00.000Z` from typeorm.

Please share your data model and mysql version.

**Comment by chriskalmar** [comment]
this is the exact same version as the one used in the integration tests.
and looking at the tests proves correct behaviour: https://github.com/typeorm/typeorm/blob/master/test/github-issues/1716/issue-1716.ts#L144-L159

my next suspicion was that the underlying MySql driver might be tampering with the timezone and indeed there is a connection setting for that.

did you by any chance set `timezone` in the connection options? 
http://typeorm.io/#/connection-options/mysql--mariadb-connection-options

**Comment by cometta** [comment]
Hello Chris, i checked before reply to this mail. we do not use timezone is the connection option. Add on, I did mentioned that it returns correctly on 0.1.17  as 2018-01-31T16:00:00.000Z. 

I reconfirmed by checking the database server time with below command 
# date +"%Z %z"
SGT +0800

meanwhile, I am investigating as well, i will post if found anything. Do let me know if you have other thought.

**Comment by chriskalmar** [comment]
well, in the meantime I tested the `timezone` connection setting and this way I could reproduce the problem. it's like we both get contradicting results. 🤔

another thing that might shed some light on the matter:
```
mysql> SELECT @@global.time_zone, @@global.system_time_zone;
```

**Comment by cometta** [comment]
both version 0.1.17 and 0.1.19 return
@@global.time_zone. @@global.system_time_zone
SYSTEM              SGT

**Comment by chriskalmar** [comment]
I'm running out of ideas. could you please try one more thing:
in the connection options add `timezone: '-8'`.

**Comment by chriskalmar** [comment]
I was playing around with the mysql driver directly and the `timezone` options gave me strange results. It looks like it's not typeorm related. 

In your connection options you can turn on logging (`logging: true`) and there you will see how typeorm sends the timestamp to mysql.
I can confirm that mysql stores the timestamps not in UTC but rather does recalculate (based on server timezone) and store them without timezone information. this is far from perfect.
I'm used to postgres where you can decide if your want timezone information included or not with your timestamps.

So maybe your best bet is to go with UTC on the server. There seems to be an option for that:
https://dev.mysql.com/doc/refman/5.7/en/mysqld-safe.html#option_mysqld_safe_timezone
You could also go with a docker based mysql server which works for me without issues:
https://hub.docker.com/_/mysql/

I'm sorry that I can't give you better news. I would advise you to switch to a better database like postgres. Maybe you'd like to give it a spin ☺️

**Comment by chriskalmar** [comment]
well, some test results:
- server is set to `+2`
- mysql server is set to `+8`
- tested both via typeorm and via mysql module directly 


#### 1) regular connection:
- sent `2018-01-01 00:00:00+08`
- mysql stored `2017-12-31 17:00:00`
- received `2017-12-31T16:00:00.000Z`

mysql stores a wrong value but reading it out gives you the desired UTC time.
if you work with stored procedures in mysql this might be an obstacle.


#### 2) connection with timezone option set to `+8`:
- sent `2018-01-01 00:00:00+08`
- mysql stored `2017-12-31 16:00:00`
- received `2017-12-31T08:00:00.000Z`

setting the timezone on connection to the same as your database will let mysql store the correct UTC time but on read you will get a wrong time.

#### 3) connection with timezone option set to `-8`:
- sent `2018-01-01 00:00:00+08`
- mysql stored `2017-12-31 16:00:00`
- received `2018-01-01T00:00:00.000Z`

setting the timezone on connection to the reversed timezone of your database will let mysql store the correct UTC time but on read you will get a wrong time.

#### 4) connection with timezone option set to `+0`:
- sent `2018-01-01 00:00:00+08`
- mysql stored `2017-12-31 16:00:00`
- received `2017-12-31T16:00:00.000Z`

now, if you set the timezone to `+0` on connection mysql will store correctly the UTC time and even on read you will receive the correct UTC time. 

so 4) should do the trick. 
please let me know if it works for you as well.

**Comment by cometta** [comment]
i tried option 4, able to store in mysql correctly in UTC. but when retrieve, it still 2018-01-31T16:00:00+08:00  . +8:00 as the timezone

**Comment by chriskalmar** [comment]
how is that even possible?
the initial information about the timezone `+8` is gone once it's persisted to the database.
furthermore I'm pretty sure `2018-01-31T16:00:00+08:00` is not a date object but rather a string representation of such. 

can you check if the database table was defined correctly:
`describe my_table_name;`

**Comment by cometta** [comment]
ignore the string, that was moment output. When retrieve from mysql, i get  2018-01-31T08:00:00.000Z  .  describe my_table_name, show the field is datetime. In mysql it is showing as 2018-01-31 16:00:00

**Comment by chriskalmar** [comment]
can you turn on typeorm logging and check the query that fetches the timestamp?
and run it in the mysql interface as well to check what results you get.

I checked typeorm source again and there is no UTC conversion whatsoever going on.
right now, I can't tell where it happens. the worst part is that I can't recreate the same behaviour even though we have the same mysql server version and the same timezone setup.
non-reproducible bugs are my favourite ones 😜

**Comment by cometta** [comment]
yes, i copied and paste the sql statement from logging and pasted in mysql, the output is in UTC. I also try with entityManager.query('select * from table_name'); and it output 2018-01-31T08:00:00.000Z   . Are you tying with 0.1.19?

**Comment by chriskalmar** [comment]
I tried with `0.1.18` and `0.1.19`, same results.
let's see if node is doing something to the dates.

what results do you get for:
```
node -p 'new Date("2018-05-01 00:00:00+8")'
```
and
```
node -p 'new Date("2018-05-01 00:00:00+8").getTimezoneOffset()'
```

**Comment by cometta** [comment]
$ node -p 'new Date("2018-05-01 00:00:00+8")'
2018-04-30T16:00:00.000Z
$ node -p 'new Date("2018-05-01 00:00:00+8").getTimezoneOffset()'
-480

**Comment by cometta** [comment]
i will post when i found anything. i investigating on this file https://github.com/typeorm/typeorm/commit/145212a77aedfeaf908f9d398699d668f26ad074#diff-f0f40758177783349c31da1ee0725add

**Comment by cometta** [comment]
i traced the file SelectQueryBuilder.loadRawResults(..) , 
>  const results = await queryRunner.query(sql, parameters);   // line 1899
already give output 2018-01-31T08:00:00.000Z . . any other file, that you would like me to trace the output..?

**Comment by cometta** [comment]
below are my test result


0.1.17
---
Without typeorm timezone option 
Code: new Date('2018-02-01T00:00:00+08:00');
logging Insert : 2018-01-31T08:00:00.000Z
After em.save() return 2018-01-31T16:00:00.000Z --> correct UTC
Mysql interface : 2018-01-31 16:00:00  --> correct UTC
em.query('select * table_name') : 2018-01-31T08:00:00.000Z  --> wrong???
em.findOne() : 2018-01-31T16:00:00.000Z, -->correct
em.createQueryBuilder() :  2018-01-31T16:00:00.000Z -->correct

>0.1.19
--
with typeorm option timezone: 'Z'
Code: new Date('2018-02-01T00:00:00+08:00');
logging Insert : 2018-01-31T16:00:00.000Z  --> correct UTC
After em.save() return 2018-01-31T16:00:00.000Z   ---> correct UTC
Mysql interface: 2018-01-31 16:00:00 --> correct UTC
em.query('select * table_name') : 2018-01-31T08:00:00.000. ---> incorrect 
em.findOne(): 2018-01-31T08:00:00.000Z,  ---> incorrect
em.createQueryBuilder() :  2018-01-31T08:00:00.000Z --> incorrect

**Comment by cometta** [comment]
i created a small test case, can you help to run it and let's compare output

```
@Entity()
export class TestMysql {
  @PrimaryGeneratedColumn() id: number;

  @Column({ name: 'date_test', nullable: false })
  dateTest: Date;
}

        await getManager('main').transaction(async entityManager => {
          const testMysql = new TestMysql();
          testMysql['dateTest'] = new Date('2018-02-01 00:00:00+08');
          const saveResult = await entityManager.save(TestMysql, testMysql);
          console.log('-------saveResult-------');
          console.log(saveResult);

          const queryResult = await entityManager.query(
            `select * from test_mysql where id=${saveResult['id']}`
          );
          console.log('-------queryResult-------');
          console.log(queryResult);

          const findOneResult = await entityManager.findOne(TestMysql, { id: saveResult['id'] });
          console.log('-------findOneResult-------');
          console.log(findOneResult);

          const createQueryBuilderResult = await entityManager
            .createQueryBuilder(TestMysql, 'testMysql')
            .where({ id: saveResult['id'] })
            .getMany();
          console.log('-------createQueryBuilderResult-------');
          console.log(createQueryBuilderResult);
        });

```


0.1.17 without typeorm timezone option 
-------saveResult-------
TestMysql { dateTest: 2018-01-31T16:00:00.000Z, id: 2 }
executing query:  select * from test_mysql where id=2
-------queryResult-------
[ TextRow { id: 2, date_test: 2018-01-31T08:00:00.000Z } ]
executing query:  SELECT `TestMysql`.`id` AS `TestMysql_id`, `TestMysql`.`date_test` AS `TestMysql_date_test` FROM `test_mysql` `TestMysql` WHERE `TestMysql`.`id`=? -- PARAMETERS: [2]
-------findOneResult-------
TestMysql { id: 2, dateTest: 2018-01-31T16:00:00.000Z }
executing query:  SELECT `testMysql`.`id` AS `testMysql_id`, `testMysql`.`date_test` AS `testMysql_date_test` FROM `test_mysql` `testMysql` WHERE `testMysql`.`id`=? -- PARAMETERS: [2]
-------createQueryBuilderResult-------
[ TestMysql { id: 2, dateTest: 2018-01-31T16:00:00.000Z } ]






0.1.19 with typeorm timezone option 'Z' 
-------saveResult-------
TestMysql { dateTest: 2018-01-31T16:00:00.000Z, id: 3 }
executing query:  select * from test_mysql where id=3
-------queryResult-------
[ TextRow { id: 3, date_test: 2018-01-31T08:00:00.000Z } ]
executing query:  SELECT `TestMysql`.`id` AS `TestMysql_id`, `TestMysql`.`date_test` AS `TestMysql_date_test` FROM `test_mysql` `TestMysql` WHERE `TestMysql`.`id`=? -- PARAMETERS: [3]
-------findOneResult-------
TestMysql { id: 3, dateTest: 2018-01-31T08:00:00.000Z }
executing query:  SELECT `testMysql`.`id` AS `testMysql_id`, `testMysql`.`date_test` AS `testMysql_date_test` FROM `test_mysql` `testMysql` WHERE `testMysql`.`id`=? -- PARAMETERS: [3]
-------createQueryBuilderResult-------
[ TestMysql { id: 3, dateTest: 2018-01-31T08:00:00.000Z } ]
executing query:  COMMIT

**Comment by cometta** [comment]
for your last case 0.1.19 - without timezone config , can you check whether it is stored as UTC . can paste the result here. mine is not stored in mysql as utc.

**Comment by chriskalmar** [comment]
ok, I think I know what's causing the difference. even on my side I had results that diverted from prior tests. 
I was trying your mysql driver `mysql2` and since then things stopped producing correct results.
try to remove `mysql2`, install `mysql` and set the timezone option to `+0`.

this should at least give you correct results with typeorm and on the database side as well. 
once we've established that deciding on the right mysql driver will be a different topic altogether.

**Comment by chriskalmar** [comment]
looks like there is an easy fix for using `mysql2`. 
`mysql2` doesn't have a `timezone` setting in the connection config but it respects the `TZ` environment setting.

try this:
```
TZ=UTC  <your node command>
```

**Comment by chriskalmar** [comment]
great, I'm glad it finally works for you.  🎉
to sum it up for others that might have the same issue there are 2 solutions based on the underlying mysql driver in use:

#### 1) with `mysql`:
set `timezone` option in typeorm to `+0`

#### 2) with `mysql2`:
run the node process with the timezone environment variable `TZ=UTC`

I think you can close the issue now

**Comment by pleerock** [comment]
@chriskalmar thank you very much for your help!

**Comment by chriskalmar** [comment]
@pleerock happy to help 😃

**Comment by chanlito** [comment]
@chriskalmar OMG thanks a lot.

**Comment by chriskalmar** [comment]
@pleerock well, this is only mysql related, so it would make sense to mention both methods (`timezone` option and `process.env.TZ`) nearby the mysql connection docs.

I work most of the time with postgres and there I don't need to set any of those options. Postgres has a great timezone support built in and it works out of the box. 
So it's not a general setting for all databases.

Maybe the best place to put it is something like `Advanced Topics` -> `Timezone support`.

**Comment by pleerock** [comment]
I also work with posgres and without process.env.TZ set to UTC it creates wrong dates (not wrong, it just treats dates read from your database as dates in a local timezone)

**Comment by chriskalmar** [comment]
What datatype are you using? `timestamp with time zone` or another one?
Because with `timestamp with time zone` it's still UTC.
I'm using a pretty standard postgres docker container (which is set to UTC by default).  I moved it to another timezone and still everything get stored correctly in UTC. When fetching data I get the expected result too.
Did you send the date in full timezone notation? (e.g. 2018-05-08 12:00:00**+2**)

**Comment by hash** [comment]
I have 0.2.18 version and setting process.env.TZ to UTC does not help

**Comment by amr-alamir** [comment]
> #### 1) with `mysql`:
> set `timezone` option in typeorm to `+0`
> #### 2) with `mysql2`:
> run the node process with the timezone environment variable `TZ=UTC`

This is not working for me

I found a solution that worked from [this stakoverflow answer](https://stackoverflow.com/a/69669088/13940475):

>What worked for me was setting the timezone info manually upon starting the server:
> ``await manager.query(`SET GLOBAL time_zone = '+00:00';`)``
> ``await manager.query(`SET time_zone = '+00:00';`)``

**Comment by aixiamomo** [comment]
`ConnectionOptions.timezone`，This can be 'local', 'Z', or an offset in the form +HH:MM or -HH:MM，https://github.com/mysqljs/mysql#connection-options

if set '+8'，The data you read from mysql is correct，but write to mysql is  incorrect, typeorm will send to mysql use utc format，so `timezone` need use '+8:00'.

```typescript
/**
 * convert zone to +HH:MM
 * 'Z' => 'Z'
 * '+8' => '+08:00'
 * '0600' => '+06:00'
 */
function convertZone (zoneString: string): string {
  if (zoneString.toUpperCase() === 'Z') { return 'Z' }
  const offset = Number(zoneString) || zoneString
  return moment().utcOffset(offset).format('Z')
}

```
