### ISSUE TITLE
Foreign key dropped on every sync and Unique Index created

### ISSUE THREAD

**Issue by Ionaru** [typeorm/typeorm#2137]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
When adding a one-to-one relation between two entities, a foreign key will be recreated on every startup after the one-to-one relation is created. Also a unique index is recreated on every startup after being created with the relation.

When the entities with relation are created in an empty database, then to foreign key will not be recreated on startup and the unique index won't be created at all.

Steps to reproduce
1. Have a simple setup with two existing entities.
2. Add a one-to-one relation between the entities
3. Restart the script
4. The same SQL with ALTER queries will run on startup each time.

Reproduction Gist: https://gist.github.com/Ionaru/9d01b6e5538e577bcea5e694728eee78

```sql
START TRANSACTION
SELECT DATABASE() AS `db_name`
SELECT * FROM `INFORMATION_SCHEMA`.`TABLES` WHERE (`TABLE_SCHEMA` = 'web_evetrack_test_2' AND `TABLE_NAME` = 'foo') OR (`TABLE_SCHEMA` = 'web_evetrack_test_2' AND `TABLE_NAME` = 'bar')
SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE (`TABLE_SCHEMA` = 'web_evetrack_test_2' AND `TABLE_NAME` = 'foo') OR (`TABLE_SCHEMA` = 'web_evetrack_test_2' AND `TABLE_NAME` = 'bar')
SELECT * FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` WHERE `CONSTRAINT_NAME` = 'PRIMARY' AND ((`TABLE_SCHEMA` = 'web_evetrack_test_2' AND `TABLE_NAME` = 'foo') OR (`TABLE_SCHEMA` = 'web_evetrack_test_2' AND `TABLE_NAME` = 'bar'))
SELECT `SCHEMA_NAME`, `DEFAULT_CHARACTER_SET_NAME` as `CHARSET`, `DEFAULT_COLLATION_NAME` AS `COLLATION` FROM `INFORMATION_SCHEMA`.`SCHEMATA`
SELECT `s`.* FROM `INFORMATION_SCHEMA`.`STATISTICS` `s` LEFT JOIN `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` `rc` ON `s`.`INDEX_NAME` = `rc`.`CONSTRAINT_NAME` WHERE ((`s`.`TABLE_SCHEMA` = 'web_evetrack_test_2' AND `s`.`TABLE_NAME` = 'foo') OR (`s`.`TABLE_SCHEMA` = 'web_evetrack_test_2' AND `s`.`TABLE_NAME` = 'bar')) AND `s`.`INDEX_NAME` != 'PRIMARY' AND `rc`.`CONSTRAINT_NAME` IS NULL
SELECT `kcu`.`TABLE_SCHEMA`, `kcu`.`TABLE_NAME`, `kcu`.`CONSTRAINT_NAME`, `kcu`.`COLUMN_NAME`, `kcu`.`REFERENCED_TABLE_SCHEMA`, `kcu`.`REFERENCED_TABLE_NAME`, `kcu`.`REFERENCED_COLUMN_NAME`, `rc`.`DELETE_RULE` `ON_DELETE`, `rc`.`UPDATE_RULE` `ON_UPDATE` FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` `kcu` INNER JOIN `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` `rc` ON `rc`.`constraint_name` = `kcu`.`constraint_name` WHERE (`kcu`.`TABLE_SCHEMA` = 'web_evetrack_test_2' AND `kcu`.`TABLE_NAME` = 'foo') OR (`kcu`.`TABLE_SCHEMA` = 'web_evetrack_test_2' AND `kcu`.`TABLE_NAME` = 'bar')
DROP INDEX `IDX_87b3a1a751e750a943188661ec` ON `foo`
ALTER TABLE `foo` DROP FOREIGN KEY `FK_87b3a1a751e750a943188661ec0`
ALTER TABLE `foo` ADD UNIQUE INDEX `IDX_87b3a1a751e750a943188661ec` (`barId`)
ALTER TABLE `foo` ADD CONSTRAINT `FK_87b3a1a751e750a943188661ec0` FOREIGN KEY (`barId`) REFERENCES `bar`(`id`)
COMMIT

```

**Comment by Fiiii** [comment]
☝️ Same here, I figure out that it happen also in my project, every time that I generate new migration it will do the same, ie. add { unique: true } to @Index() decorator in entity generate new migration, run it, and generate again. It will generate second identical migration 😞 ... waiting for response !

**Comment by bhram** [comment]
same here , i hope to fix that :(

**Comment by lijax** [comment]
same here

**Comment by chrismcleod** [comment]
I also had this problem for a uuid primary key.  

The database driver will compare database metadata to entity metadata created using the decorators.  In my case, the check for `column.isGenerated !== metadata.isGenerated` failed so it was recreating the foreign key.  

The reason seemed to be that I had declared my uuid primary key as `@PrimaryGeneratedId('uuid')` but when I first created the migration, i had not set `isGenerated` to true for that column.  By adding directly to my database (or create a migration) a default value for the uuid column, `uuid_generate_v4()`, it stopped dropping the foreign key on sync.

If your issue is related but not quite the same, you may can track down the cause by adding some console.logs directly to the source in node_modules.  Start with these files:

https://github.com/typeorm/typeorm/blob/master/src/schema-builder/RdbmsSchemaBuilder.ts#L126

https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L707

**Comment by Kononnable** [comment]
Problem has been fixed recently. Fixed version can be installed by using `typeorm@rc`. It doesn't recreate foreign key every time. However it still needs one more schema sync/migration to create proper db schema(it adds two unique indices on new column at first).

**Comment by pleerock** [comment]
fix should be available in `0.2.10`

**Comment by renilbabu03** [comment]
It worked for me after i made synchronize = false in @Entity

`@Entity( {name:"table-name",
                synchronize:false})`

**Comment by danbruce** [comment]
This is still happening for me on `0.2.20` with MySQL. Every time I synchronize, my unique index that includes a foreign key tries to get dropped and recreated. Since it's the only index on that foreign key, MySQL complains about dropping a required index for a foreign key.

**Comment by cossay** [comment]
I'm facing the same problem on 0.2.21.

**Comment by igortobert** [comment]
0.2.24 same problem (sync: true) DROP CONSTRAINT, DROP COLUMN and i lost my relations

**Comment by Ionaru** [comment]
@pleerock Sounds like a regression, maybe this ticket should be re-opened?

**Comment by kugland** [comment]
I’m still seeing this behavior with version 0.2.25.

**Comment by jameshmread** [comment]
Seeing this issue in 0.2.30 as well. I was struggling with this for hours. It appears to be something to do with the @PrimaryGeneratedColumn('uuid') decorator. I'm not exactly sure what is going on but hope this can point maintainers in the right direction.
My entities (other columns removed for brevity).
```typescript
@Entity('StaffAvailabilities')
export class StaffAvailability {
  @PrimaryGeneratedColumn('uuid')
  id?: string;

  @ManyToOne(() => Shift, {
    nullable: false,
    primary: true,
    onDelete: 'NO ACTION',
  })
  shift?: Shift;

}
```
```typescript
@Entity('Shifts')
export class Shift {
  @PrimaryGeneratedColumn('uuid')
  id?: string;

  @ManyToOne(
    () => Rota,
    r => r.shifts,
  )
  rota?: Rota;

}
```
Running on MySQL: 8.0.18-google (hosted on GCloud MySQL)
The ORM would create the tables just fine and would rebuild and re-sync fine. Until I inserted items into the `StaffAvailabilities` table. On the *Next* restart with no code changes. It would drop the Foreign key referencing the `Shifts` table and then complain that the reference didn't exist.

**The only thing that worked was to change the `@PrimaryGeneratedColumn('uuid')` in *both* files. 
To this `@PrimaryColumn({ generated: 'uuid' })` drop both tables and then recompile and re-sync. Then the issue is fixed.**

**Comment by Marinets** [comment]
Same problem again

query: ALTER TABLE `notifications` DROP PRIMARY KEY
query: ALTER TABLE `notifications` DROP COLUMN `id`
query: ALTER TABLE `notifications` ADD `id` varchar(36) NOT NULL PRIMARY KEY
query failed: ALTER TABLE `notifications` ADD `id` varchar(36) NOT NULL PRIMARY KEY
error: Error: ER_DUP_ENTRY: Duplicate entry '' for key 'PRIMARY'

Framework NestJS
typeorm 0.3.16 (0.3.12 the same problem)

**Comment by LuckyArdhika** [comment]
Im my case, there is any duplicate entity with same name in my project, its happen when you use directory glob pattern.

first of all is: I move my entity from folder A into folder B, its moving in root dir but the files in build/dist folder didnt synchronized with our moved files, so in my build folder is still have 2 file of duplicate entity (in folder A and folder B) with same name that cause this.

so i delete my dist/build folder then re run my app and its fixed.

you might want to check is your issue similiar with me? 
paste `console.log("utils/directoryExportedclassesloader", allFiles);` in your node_modules/typeorm/util/DirectoryExportedClassesLoader.js inside importClassesFromDirectories() function
