### ISSUE TITLE
UpdateDateColumn: multiple assignments to same column

### ISSUE THREAD

**Issue by felixle236** [typeorm/typeorm#2651]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

**Steps to reproduce or a small repository showing the problem:**

I'm getting an error when updating with postgres using UpdateDateColumn.

Columns of entity:
```
@CreateDateColumn({type: 'timestamptz'})
createdAt: Date;

@UpdateDateColumn({type: 'timestamptz'})
updatedAt: Date;
```

Update function:
```
async update(id: number, data: any): Promise<boolean> {
    if (!id || !validator.isInt(id) || !data)
        throw new ValidationError(1);

    let user = await this.userRepository.createQueryBuilder('user')
        .whereInIds([id])
        .andWhere('user.deletedAt IS NULL')
        .getOne();

    if (!user)
        throw new ValidationError(104, 'user');

    DataHelper.filterDataInput(user, data, [
        'firstName',
        'lastName',
        'gender',
        'birthday',
        'phone',
        'address',
        'culture',
        'currency'
    ]);
    user.validate();

    let result = await this.userRepository.update(id, user);
    console.log(result);
    return true;
}
```

Logging:
```
query failed: UPDATE "user" SET "id" = $2, "roleId" = $3, "firstName" = $4, "lastName" = $5, "email" = $6, "password" = $7, "avatar" = $8, "gender" = $9, "birthday" = $10, "phone" = $11, "address" = $12, "culture" = $13, "currency" = $14, "accessToken" = $15, "tokenExpire" = $16, "createdAt" = $17, "updatedAt" = $18, "deletedAt" = $19, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = $1 -- PARAMETERS: [1,1,1,"Admin","Local","admin@localhost.com","818d6f2daf098f9043b7cc5a167c883d",null,1,null,null,null,null,null,null,null,"2018-08-12T08:07:04.099Z","2018-08-12T08:07:04.099Z",null]
```

Error:
```
QueryFailedError: multiple assignments to same column "updatedAt"
```

We can see **"updatedAt" = $18** and **"updatedAt" = CURRENT_TIMESTAMP WHERE** has appeared tiwce. I just want to suggest that we should ignore CreateDateColumn and UpdateDateColumn when generate query string?

Also I have tried to update successfully, but I cannot get the status update into UpdateResult:
```
UpdateResult {generatedMaps: Array(0), raw: Array(0)}
```

Thanks so much.

**Comment by zerox12311** [comment]
I faced a same problem...

**Comment by ematipico** [comment]
Same problem here

**Comment by akosasante** [comment]
I am also facing this issue currently.

Job Entity with UpdateDate column:
```javascript
@Entity()
export class Job {
    public static isValid(jobObj: JobObject): boolean {
        return !!jobObj.startLocation && !!jobObj.endLocation;
    }
...
    @CreateDateColumn()
    public dateCreated: Date;

    @UpdateDateColumn()
    public dateModified: Date;

    @ManyToOne(type => Customer, (customer: Customer) => customer.jobs, {cascade: true})
    public customer: Customer;
...
}
```

I encountered this error when trying to write a unit test for updating the customer relation of the job entity:

```javascript
it("should change customer if different customer passed with job", async () => {
        const newCustomer: CustomerObject = {companyName: "Brand New Company"};
        const oldJobWithCustomer = await dbJob.getJobById(2, true);
        oldJobWithCustomer.customer = newCustomer;
        const newJob = await dbJob.updateJob(2, jobObj);
});
```

The above returns the error:
```error: multiple assignments to same column "dateModified"```

and this is the failed query:
```
UPDATE "test"."job" SET "id" = $1, "description" = $2, "startLocation" = $3, "endLocation" = $4, "status" = $5, "jobCost" = $6, "dateCreated" = $7, "dateModified" = $8, "customerId" = $9, "dateModified" = CURRENT_TIMESTAMP WHERE "id" = $10 RETURNING *;
               -- PARAMETERS: 2,,{"city":"Testopia","street":"9 Test St.","province":"Ontario","postalCode":"X0X0X0"},{"city":"Fakeville","street":"1 Fake Ave.","province":"Alberta","postalCode":"P9P1X0"},Ready,,Sat Oct 20 2018 23:09:19 GMT-0400 (Eastern Daylight Time),,,2
```

As with OP, the dateModified column is getting set twice, once with what I assume is the time the customer property was changed, and once with `CURRENT TIMESTAMP`. What is the recommended workaround here?

**Comment by akosasante** [comment]
So far I've worked around (or perhaps this is what's expected) by parsing the JobObject and making sure it doesn't have it's own `dateModified` property when I pass it to the `.updateJob` method.

I encountered the same thing with foreign keys/relations. Where if I update the `job.customerId` value but leave the `job.customer` object then it comes up with the same error. So I just delete `job.customer` before saving.

**Comment by sgomanf** [comment]
same issue, not happen with save method.

**Comment by pleerock** [comment]
its a bug. We need to exclude adding update column into the list if its already was set in the list provided by `set` method.

**Comment by yakartoev** [comment]
I guess you've meant exclude "updated" column, because bug not only in update column. As @akosasante , I'm getting multiple assignments to foreign key, while saving relation entities through cascades.

**Comment by danielbischoff** [comment]
Any progress here, as I have the same problem?

**Comment by felixle236** [comment]
> Any progress here, as I have the same problem?

It's still there, I must exclude that field before execute:

```delete user.updatedAt;```

There seems to be some reason that this error has not been fixed.

**Comment by pleerock** [comment]
Do not manually assign `updatedAt` column value, exclude this property from the assignment list. Value of the column decorated by `@UpdatedColumn` is controlled by orm, its the whole point of this decorator.

**Comment by knownasilya** [comment]
I'm seeing a similar issue:

<img width="309" alt="Screen Shot 2019-05-30 at 3 06 20 PM" src="https://user-images.githubusercontent.com/34726/58659192-616ff580-82f0-11e9-9056-da461ba4fc64.png">

The sql generated is : `"UPDATE "discover_result" SET "result" = $2, "profileId" = $3, "profileId" = $4, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" IN ($1) RETURNING "updatedAt""` but as you noticed in the screenshot, there are only 3 parameters.

**Comment by knownasilya** [comment]
Looks like two `profileId` column names are generated, on automatically for `profile`

```js
  @ManyToOne(_type => Profile, { eager: true, nullable: true })
  @Field(_type => Profile)
  profile: Profile;

  @Column({ nullable: true })
  profileId: string;
```

**Comment by matomesc** [comment]
I have a simple save `this.messageRepository.save(message)` which sometimes generates this incorrect query:

```sql
UPDATE "message" 
SET "customerId" = $2, 
  "checkoutId" = $3, 
  "customerId" = $4, 
  "checkoutId" = $5, 
  "updatedAt" = CURRENT_TIMESTAMP 
WHERE "id" IN ($1) RETURNING "updatedAt"
```

As you can see `customerId` and `checkoutId` are set twice.

**Note:** The parameters array is always correct - it has exactly 3 params (`id`, `customerId` and `checkoutId`)

The entity relationships are many-to-one and look like:

```ts
@ManyToOne(_type => Checkout, checkout => checkout.messages, {
  onDelete: 'SET NULL',
  onUpdate: 'RESTRICT'
})
@JoinColumn({ name: 'checkoutId' })
@Index()
public checkout: Checkout | null;

@Column('text', { nullable: true })
public checkoutId: string | null;
```
The error occurs quite rarely and I'm having a hard time reproducing but I do see it in my production app.

**Comment by kvandake** [comment]
When we get an object from a database without relations, the properties have null values.
```ts

class Post {

  @ManyToOne(type => Tag, tag => tag.posts)
  @JoinColumn({ name: 'post_id' })
  tag: Tag | null;

  @Column({ name: 'tag_id', nullable: true })
  tagId: number;
}

class Tag {
...
}


const post = await this.repository.createQueryBuilder().where({ id: 1}).getOne();
// post.tag = null;
// post.tagId = null;

post.title = "updated title";

// Error: multiple assignments to same column "tag_id"
await this.repository.save(post);

// if "tag" set to undefined 
post.tag = undefined;
post.tagId = null;

// Success
await this.repository.save(post);

```

**Comment by Ginden** [comment]
I have code that always reproduce this issue:

```typescript
const p: Post = Post.findOne({id: 42});
await connection.getRepository(Post).update({id: 42}, p);
```

**Comment by felixle236** [comment]
To resolve this issue, please use `update` option:

```
import { Column, CreateDateColumn, Entity, Index, OneToMany, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';
import { Permission } from './Permission';
import { RoleCode } from '../../config/Enums';
import { RoleSchema } from '../schemas/RoleSchema';
import { User } from './User';

@Entity(RoleSchema.TABLE_NAME)
@Index((role: Role) => [role.code, role.deletedAt], { unique: true })
@Index((role: Role) => [role.name, role.deletedAt], { unique: true })
export class Role {
    @PrimaryGeneratedColumn({ name: RoleSchema.COLUMNS.ID })
    id: number;

    @CreateDateColumn({ name: RoleSchema.COLUMNS.CREATED_AT, type: 'timestamptz', update: false })
    createdAt: Date;

    @UpdateDateColumn({ name: RoleSchema.COLUMNS.UPDATED_AT, type: 'timestamptz', update: false })
    updatedAt: Date;

    @Column('timestamptz', { name: RoleSchema.COLUMNS.DELETED_AT, nullable: true })
    deletedAt?: Date;

    @Column('smallint', { name: RoleSchema.COLUMNS.CODE })
    code: RoleCode;

    @Column({ name: RoleSchema.COLUMNS.NAME, length: 50 })
    name: string;

    @Column('smallint', { name: RoleSchema.COLUMNS.LEVEL })
    level: number;

    /* Relationship */

    @OneToMany(() => User, user => user.role)
    users?: User[];

    @OneToMany(() => Permission, permission => permission.role)
    permissions?: Permission[];
}
```

But I still got issue about foreign key, I want to define foreign key by myself. Maybe we will have `update` option for `JoinColumn` like above?

```
@Column({ name: UserSchema.COLUMNS.ROLE_ID })
roleId: number;

@ManyToOne(() => Role, role => role.users)
@JoinColumn({ name: UserSchema.COLUMNS.ROLE_ID })
role?: Role;
```

**Comment by foloinfo** [comment]
It seems like this error happens when you define some relationship and FK at the same time.

```
  @OneToOne(type => File, { eager: true, nullable: true })
  @JoinColumn({ name: 'imageId' })
  @IsOptional()
  image?: File

  @Column({ type: 'bigint', nullable: true })
  @IsOptional()
  imageId?: string
```

A definition like above caused `multiple assignments to the same column` error when updating `image` with null like `this.image = null`.
It seems like typeorm will set `image` and `imageId` as null, so it will cause multiple assignments to `imageId` when issuing UPDATE query.

I could avoid this error by adding `this.imageId = undefined` before saving data.
ex.

```
this.image = null // or maybe some image model
this.imageId = undefined
// do whatever to save data.
```

**Comment by felixle236** [comment]
@pleerock awesome 👏 
`@UpdatedColumn` decorator has been resolved. But I still got the issue about foreign key above, so can we have an option like `update` to resolve it?

**Comment by swymmwys** [comment]
@pleerock 
any updates on the same issue but with the foreign key column?

**Comment by sbadadal** [comment]
Used repository.save() instead of repository.update() and it worked. 
Verified SQL logs and I can see both Select and Update statements executed.

**Comment by evgenytk** [comment]
> @pleerock
> any updates on the same issue but with the foreign key column? 

The problem is in the eager loaded relations. Updating an FK manually while the relation property is loaded causes multiple assignments to the join column.

The solution is either don't use the eager option, e.g:
`@OneToOne(type => Profile, { eager: false, nullable: true })`
`@JoinColumn()`
`profile: Profile;`
`@Column({ nullable: true })`
`profileId: string;`

either set the relation property to undefined or delete it, e.g.:
`const user = await userRepositofy.find();`
`user.profileId = '4288fb3f-b1d9-40cb-acb8-01ef52709b1c';`
`user.profile = undefined;` or `delete user.profile;`

**Comment by imnotjames** [comment]
Agreed on that one.  If anyone still believes the FK issue is a real bug and not user error please open a new issue with more info.  For this issue it's off topic.

Closing this issue as the original problem has been solved.

**Comment by knownasilya** [comment]
Yes it's still a bug. At the least a better error message is required. Has anyone opened a new issue?

**Comment by joaohenriquesouza80** [comment]
The workaround of @evgenytk works for me. 
So many tks.

**Comment by KoushikKintali** [comment]
> @pleerock awesome 👏 `@UpdatedColumn` decorator has been resolved. But I still got the issue about foreign key above, so can we have an option like `update` to resolve it?

@pleerock any update on this, we are still facing the issue?

**Comment by SebaBoler** [comment]
Yes, issue is actual.

**Comment by shahen94** [comment]
+1

**Comment by upscripter** [comment]
The issue reappeared in version `0.3.25`. It was not present in `0.3.24`.

**Comment by alumni** [comment]
@upscripter the tests for this issue pass, so please open a new issue with proper replication steps :)
