### ISSUE TITLE
ManyToOne eager query error 

### ISSUE THREAD

**Issue by lucas-coelho** [typeorm/typeorm#2661]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have the following entities:

**PostComment**
```
@Entity()
export class PostComment  {

  @PrimaryGeneratedColumn()
  id: number;

  @Column({ default: true })
  active: boolean;

  @Column({
    type: String,
    nullable: true,
  })
  authorName?: String;

  @Column({
      type: String,
      nullable: true,
  })
  comment?: String;

  @ManyToOne(_ => Post, post => post.comments, {eager: true})
  @JoinColumn()
  post: Post;

}
```

**Post**
```
@Entity()
export class Post {

  @PrimaryGeneratedColumn()
  id: number;

  @Column({ default: true })
  active: boolean;

  @Column()
  title: string;

  @Column()
  text: string;

  @OneToMany(_ => PostComment, comment => comment.post, {
    cascade: true,
  })
  comments: PostComment[];

}
```

When try to find all PostComment with an post id:
`repository.find({ post: { id: 1 } })`

it  gives the  following error: `table name "PostComment_post" specified more than once`.

**Comment by mohamed-badaoui** [comment]
On @next version, I confirm this issue eager loading does not work on @ManyToOne relation.

It causes duplicate errors like these :
ER_NONUNIQ_TABLE: Not unique table/alias
ER_DUP_FIELDNAME: Duplicate column name

**Comment by locnguyen** [comment]
Noting that I'm encountering the same error on `0.2.11` as well. I'll see if I can find the problem but I might be in over my head.

**Comment by breytex** [comment]
I can confirm that `ManyToOne` relations with `eager:true` are not working in `0.2.11`.
I get `"ER_NONUNIQ_TABLE: Not unique table/alias: 'Session_user'"` with the following setup:

(using `type-graphql` for resolvers. Thats where `@Field` is coming from)

```typescript
export abstract class Session extends BaseEntity {
    @Field(type => ID)
    @PrimaryGeneratedColumn("uuid")
    id: string

    @Field()
    @ManyToOne(type => User, { eager: true })
    @JoinColumn()
    user: User
}
```

```typescript
// in a resolver
const session: Session = await Session.findOne({ token: cookie })
// do something with session.user
```

**Comment by breytex** [comment]
Seems to be resolved in `0.2.14`.

**Comment by F-Gueguen** [comment]
I have the same issue on nested eagered entities, the built table alias is getting longer and longer, until reaching the 63 max length (at least in postgre).
An elegant solution would be to be able to specify an optional preferred alias in the entity, or a preferred alias on the eagered field.

**Comment by Kononnable** [comment]
Closing - original issue is fixed.

@F-Gueguen your issue doesn't seem connected to that one. Please look if there is no such issue already reported and if there isn't one - make a new one.

**Comment by HoHoibin** [comment]
> On @next version, I confirm this issue eager loading does not work on @ ManyToOne relation.
> 
> It causes duplicate errors like these :
> ER_NONUNIQ_TABLE: Not unique table/alias
> ER_DUP_FIELDNAME: Duplicate column name

I've encountered same errors. It was said to be fixed in 0.2.14, but my TypeORM is in 0.2.16.

`(node:4119) UnhandledPromiseRejectionWarning: QueryFailedError: ER_DUP_FIELDNAME: Duplicate column name 'User_faculty_id'
    at new QueryFailedError (/Users/hohoibin/Developments/graduate/node/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/Users/hohoibin/Developments/graduate/node/src/driver/mysql/MysqlQueryRunner.ts:164:37)
    at Query.<anonymous> (/Users/hohoibin/Developments/graduate/node/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/Users/hohoibin/Developments/graduate/node/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/Users/hohoibin/Developments/graduate/node/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/hohoibin/Developments/graduate/node/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/Users/hohoibin/Developments/graduate/node/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/hohoibin/Developments/graduate/node/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/hohoibin/Developments/graduate/node/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/hohoibin/Developments/graduate/node/node_modules/mysql/lib/Connection.js:91:28)
(node:4119) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4119) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by breitsmiley** [comment]
I confirm the error in version 0.2.16

Some observations:

1. **This throw ER_DUP_FIELDNAME exception**

```    
@ManyToOne(type => Currency, {
        eager: true,
})
@JoinColumn({name: 'currency_id'})
```

2. **All of this variants work perfectly:**

2.1 without eager
``` 
@ManyToOne(type => Currency)
@JoinColumn({name: 'currency_id'})
currency: Currency
``` 

2.1 without custom field name
``` 
@ManyToOne(type => Currency, {
        eager: true,
})
@JoinColumn()
currency: Currency
``` 

2.2 With field name other than **currency_id** in my case
``` 
@ManyToOne(type => Currency, {
        eager: true,
})
@JoinColumn({name: 'other_name_id'})
currency: Currency
```

**Comment by sgarner** [comment]
Still experiencing this bug, as described above, with TypeORM version `0.2.18`.

Can the issue be re-opened for examination?

**Comment by volnyansky** [comment]
I've solved similar bug with custom naming strategy
`
class NamingStrategy extends DefaultNamingStrategy {
    eagerJoinRelationAlias(alias: string, propertyPath: string): string {
        let out = alias + '_' + propertyPath.replace('.', '_')
        let match = out.match(/_/g) || []
        return out + match.length
    }
}
    await createConnection(
        Object.assign(connectionOptions, {
            namingStrategy: new NamingStrategy(),
        })
    )
`

**Comment by scott-ho** [comment]
same error with eager: true for entity when using querybuilder, version: 0.2.19

**Comment by revbingo** [comment]
Also experiencing this, 0.2.25

**Comment by vuki656** [comment]
Experiencing the same issue on `@OneToMany`

Version:  0.2.25

**Comment by suxin2017** [comment]
Also experiencing this, 0.2.25

**Comment by vuki656** [comment]
After some digging, I realized this error is due to Typeorm creating some kind of variable when using eager loading that is more than Postgres limit for names.

For example, if you are eager loading `products `with `customer`, typeorm will create something along the lines of `customer_products`, connecting the two. If that name is longer than 63 bytes (Postgres limit) the query will crash.

I'm not 100% sure about how everything works under the hood but this is the summary of it I think.

**Comment by matthewberryman** [comment]
@vuki656 The reported error is happening for names where the length is well-shorter than 63 bytes according to OP example, though, and that case seems fixed. And #7106 is very specific to sequence length generation (c.f. #7115 ) mismatch between PostgreSQL and TypeORM's (now fixed) algorithm. If you've got an example where there is a limit here that is an issue, perhaps file as a separate issue with your example and I can take a look.

**Comment by vuki656** [comment]
> @vuki656 The reported error is happening for names where the length is well-shorter than 63 bytes according to OP example, though, and that case seems fixed. And #7106 is very specific to sequence length generation (c.f. #7115 ) mismatch between PostgreSQL and TypeORM's (now fixed) algorithm. If you've got an example where there is a limit here that is an issue, perhaps file as a separate issue with your example and I can take a look.

Good point. Ill write up an example when I get the time. It was a while ago when I encountered this problem.
