### ISSUE TITLE
AutoSync runs before Migrations

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#346]
Autosync doesn't always work on type safe database like postgres.

I have a TEXT column that was supposed to be a Boolean.

(node:67913) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): error: column "isUnclear" cannot be cast automatically to type boolean

I wrote a migration:

import {Connection, EntityManager, MigrationInterface, QueryRunner} from "typeorm";

```
export class TransformIsUnclear1489444496065 implements MigrationInterface {
  
  public async up(queryRunner: QueryRunner, connection: Connection, entityManager?: EntityManager): Promise<any> {
    try {
      let query1 = `ALTER TABLE d_t_o_modifier ALTER COLUMN "isUnclear" DROP DEFAULT;`
      let query2 = `ALTER TABLE d_t_o_modifier ALTER "isUnclear" TYPE bool USING CASE WHEN "isUnclear" = 'false' THEN FALSE ELSE TRUE END;`
      let query3 = `ALTER TABLE d_t_o_modifier ALTER COLUMN "isUnclear" SET DEFAULT FALSE;`
      let responsea = await queryRunner.query(query1);
      let responseb = await queryRunner.query(query2);
      let responsec = await queryRunner.query(query3);
    } catch (e) {
      console.log(e);
      throw e;
    }
  }
  
  public async down(queryRunner: QueryRunner, connection: Connection, entityManager?: EntityManager): Promise<any> {
  }
 
}
```

But the AutoSync error still occurs before the migration is run.

Expected Behavior: AutoSync should run AFTER migrations so edge cases can be handled.

**Comment by pleerock** [comment]
looks like your error because you didn't wrote migration correctly. You need to transform exist data in columns correct way before you change column type. I didn't understand how schema sync is related to this issue.

**Comment by rightisleft** [comment]
Im not sure i follow. I've run the migration raw in PSQL and it transforms the column as expected. I then reverts and run with migrations & autosync and it fails. 

I put break point inside the migration, and they do not hit. 
The AutoSync error is thrown.

**Comment by pleerock** [comment]
Im not sure to be honest what is correct order should be. Right now schema sync is executed before migrations. If we do inverse it may work, however what about first-time schema sync? By current design schema sync and migration should not be used together. You should use schema sync only first time you deploy the app, next time you deploy the app you just run your migrations, because schema sync cant guarantee you that you'll not loose your data, thats why you control it using your migrations only.

**Comment by rightisleft** [comment]
Good comment. How about a config param for firstTimeSchemaSync.

Once it has successfully executed, it stores an entry in the migrations table preventing it from being run in the future.

**Comment by pleerock** [comment]
no, this option wont be obvious and make things confusing. Simply use CLI instead. Those options in connection wasnt created for production, they was just created for development purposes.

**Comment by rightisleft** [comment]
The CLI isn't always an option in deployed environment.

**Comment by pleerock** [comment]
why? in any deployed environment you execute commands. Simply create a script you need to execute cli commands

**Comment by rightisleft** [comment]
Many cloud hosting providers advise against that approach. Thats the whole point of having your build server generate a distribution bundle. The end bundle that goes to production on environment like Heroku ends up being pure Javascript & Migrations. Production servers should never know about Typescript.

**Comment by rightisleft** [comment]
To use correctly, the CLI would need to generate an artifact that does not have any dependencies on tsc

**Comment by rightisleft** [comment]
**Assertion 1:** 
'sync' implies that there is something to keep in sync. An empty database is different than a populated database. 

-- Sync should be reserved for updating _existing_ entities. 
-- New entities should be auto-added ONLY if an initial schema has already been applied to the database, and tables exist. 

**Assertion 2:** 
A developer should have control over how and when to initially populate a database. This should be done through a schema artifact in source control.

_Goal:_ 
Expose a CLI command to generate a baseline schema file that can be checked into source control. The schema itself is still derived from referenced entities. 

This seeding process will only be run if the defined database contains no tables. (first time or on all tables having been dropped)

_Edge Case:_ 
If i rerun the same CLI command after being in production for months, the same schema file itself will be over written, but nothing will happen at runtime. 

_Edge Case:_ 
If i'm recreating my database after being in production for months, i might want to generate a new master schema and delete my migrations for the local developer machine. 

**Assertion 3:** 
In order to allow auto column sync, a developer sometimes needs to be able to run pre-emptive migrations. The symptoms requiring these migrations surface at author time when the entity declaration is changed and run on the developers machine. 

_Goal:_ 
Migrations need to run BEFORE auto sync to handle edge cases.

**Comment by rightisleft** [comment]
Anyone have thoughts on this? Definitely looking for feedback.

**Comment by rightisleft** [comment]
This ticket should get some love!

**Comment by pleerock** [comment]
I agree process we have right now is basic and need improvements, and that quite a big work. Migrations is a big topic and I'll come back to it later once I finish some other tasks.  Until that Im expecting people to leave as much feedback as possible :)

**Comment by artaommahe** [comment]
Same issue here - only bundled code (webpack + bundling to single binary via pkg) deployed to dev/prod environments and runs in docker container. Need a way to autoapply only migrations that imported directly to main bundle and passed as functions array to `createConnection`

**Comment by AlexMesser** [comment]
please check this issue on latest `@next` version. It should be fixed.

**Comment by rightisleft** [comment]
@AlexMesser - can you point me to documentation how to to initially populate a production database? 
It would be great if the documentation covered the approach between design time sync and production.

**Comment by pleerock** [comment]
@rightisleft probably best if you keep your database connection settings in env variables in production. That's it.

**Comment by binki** [comment]
Could this be reopened? It looks to me in latest that synchronization still happens before migrations: https://github.com/typeorm/typeorm/blob/d4e9c3e3fd9ab5e4ba2b4bcf8749824382bf8a1e/src/connection/Connection.ts#L194

I don’t want to lose data but I also want to do as little work as possible. If I can run migrations prior to synchronization, I can do any column renames, etc., if I carefully write my migrations to be conditional (e.g., only rename a column to the new name if the column with the new name doesn’t exist yet) while still letting synchronization create new tables and drop removed ones I don’t care about.

It might not be perfectly safe, but for people who know what they’re doing and want more control (e.g., hand-writing migrations), this would be a helpful feature.

**Comment by binki** [comment]
Ah, I realized that one doesn’t need to use the CLI, as discussed above, to change the order. Since you can call `runMigrations()` and `synchronize()` directly, simply set them to false in your settings and then call directly. For example:

```ts
export async function buildConnectionPromise() {
  const connection = await createConnection({
    type: 'postgres',
    entities,
    migrations,
    migrationsRun: false,
    synchronize: false,
    url: process.env.TYPEORM_URL,
  });
  // typeorm’s built-in migrations/synchronization code runs the two processes out
  // of order. Run migrations first so that they have a chance to fix column names, etc.,
  // prior to running synchronize. When using this pattern, your migrations must be written
  // conditionally because if you run this on an empty database the migrations will have no
  // tables to work with so they should all be smart enough to skip themselves so that the
  // synchronize step at the end can initialize everything. Be careful—this may save work but
  // you are likely to get things out of sync!
  await connection.runMigrations();
  await connection.synchronize();
  return connection;
}
```

**Comment by deusimardamiao** [comment]
> Ah, I realized that one doesn’t need to use the CLI, as discussed above, to change the order. Since you can call `runMigrations()` and `synchronize()` directly, simply set them to false in your settings and then call directly. For example:
> 
> ```ts
> export async function buildConnectionPromise() {
>   const connection = await createConnection({
>     type: 'postgres',
>     entities,
>     migrations,
>     migrationsRun: false,
>     synchronize: false,
>     url: process.env.TYPEORM_URL,
>   });
>   // typeorm’s built-in migrations/synchronization code runs the two processes out
>   // of order. Run migrations first so that they have a chance to fix column names, etc.,
>   // prior to running synchronize. When using this pattern, your migrations must be written
>   // conditionally because if you run this on an empty database the migrations will have no
>   // tables to work with so they should all be smart enough to skip themselves so that the
>   // synchronize step at the end can initialize everything. Be careful—this may save work but
>   // you are likely to get things out of sync!
>   await connection.runMigrations();
>   await connection.synchronize();
>   return connection;
> }
> ```

it saved me

**Comment by Form1ca** [comment]
> ```ts
> buildConnectionPromise
> ```

how use it with nestjs?
`    TypeOrmModule.forRootAsync({
      useFactory: () => connectionOptions,
    }),`
