### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by aaska** [typeorm/typeorm#3638]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[x] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Since Typeorm 0.2.12, I'm having this issue:

```
Cannot read property 'filter' of undefined
Function.EntityMetadata.difference
    EntityMetadata.js:425:27
OneToManySubjectBuilder.buildForSubjectRelation
    OneToManySubjectBuilder.js:136:13
<unknown>
    OneToManySubjectBuilder.js:35:22
<unknown>
    OneToManySubjectBuilder.js:31:48
OneToManySubjectBuilder.build
    OneToManySubjectBuilder.js:30:22
EntityPersistExecutor.<anonymous>
    EntityPersistExecutor.js:97:86
step
    tslib.js:133:26
Object.next
    tslib.js:114:56
````

The code in the project is working well with typeorm@0.2.11

I've created a small project that reproduce the issue : https://github.com/aaska/typeormbugTest
(ps: this repository is not configured to work with android, only iOS simulator)

I've tried to dig the issue as much as I could, and it seems that when I try to update the eager relation (holdings), the lazy relation (movements) is not getting properly loaded in the relations when saving the account which is causing the exception.

Let me know if you need any additional information !

Thank you for the great job !

**Comment by rvenugopal** [comment]
Can confirm that that this issue is reproducible with typeorm@0.2.12.  Works fine with typeorm@0.2.11

**Comment by aaska** [comment]
I realized that it may be related to #3576. It seems to be the same issue.

Thanks

**Comment by vlapo** [comment]
@aaska your problem is resolved in latest version 0.2.14?

**Comment by aaska** [comment]
@vlapo Yes, 0.2.14 seems to have resolved this specific issue, though it seems there now another unexpected behavior that was not present on 0.2.11.

I'm checking whether it could come from my code or it's something from typeorm - basically, it seems that if I'm trying to update an entity multiple times in sequence, the lazy table gets inserted with new values, but then gets immediately updated to empty values. Or, the entity.save() keeps inserting already inserted values.

Will create a new ticket if I can reproduce it in my test git.

Thank you !

**Comment by seawatts** [comment]
I am getting this same bug now on `0.2.25`

**Comment by TheCoordinator** [comment]
Yes, can confirm still having this issue on `0.2.29`. It happens when trying to save an object which has a lazy many to many relationship without setting that relationship again. If you set the property with a `Promise.resolve(...)` all works fine. Believe it's worth reopening this issue again.
