### ISSUE TITLE
Relationships only work when both primary keys have the same name

### ISSUE THREAD

**Issue by bijeebuss** [typeorm/typeorm#56]
Heres my two classes

```
@Table()
export class AccessToken {
  @PrimaryColumn()
  access_token: string;
}

@Table()
export class User {
  @PrimaryColumn("int", { generated: true })
  id: number;

  @Column()
  email: string;

  @OneToOne(type => AccessToken)
  @JoinColumn()
  access_token: AccessToken;
}
```

Heres what I used to persist

```
var token = new AccessToken();
token.access_token = '12345';
var user = new User();
user.email = 'mwelnick@test.com'
user.access_token = token;

return connection.getRepository(AccessToken).persist(token).then(token => {
  return connection.getRepository(User).persist(user);
})
.then (user => {
  // doesn't get here
})
```

when persisting the user I get the error 
`Error: ER_BAD_FIELD_ERROR: Unknown column 'AccessToken.id' in 'where clause'

But when i rename the primary column on AccessToken to "id" or rename them both to "primaryKey" it works. Also when I use "key" instead of id I get a sql syntax error when persisting.

**Comment by pleerock** [comment]
You are right, its a bug, I'll work on fix of this

**Comment by pleerock** [comment]
@bijeebuss can you take a look on the tests I have added? Because test is passing, but I made there everything you described in this issue

**Comment by pleerock** [comment]
what db are you using btw?

**Comment by pleerock** [comment]
also in the same test I have replaced "id" with "key" and its still passes

**Comment by bijeebuss** [comment]
I'll check it out when I have some time, tomorrow maybe. I'm using MySQL.

**Comment by pleerock** [comment]
try to install latest typeorm version, maybe it was resolved in latest version

**Comment by bijeebuss** [comment]
I don't think those tests are going to hit the issue. It isn't necessarily custom column names that causes it for me. Its when the primary columns have different names. Also I didn't use the name field on ColumnOptions in the decorator, I just had it use the actual property name.

**Comment by bijeebuss** [comment]
are the latest changes in pm or do i need to add the project to mine?

**Comment by pleerock** [comment]
they are in npm

**Comment by bijeebuss** [comment]
I'm still getting the same error. Could it be because I'm not using await or the entity manager?

**Comment by pleerock** [comment]
nope, should not

**Comment by pleerock** [comment]
did you fix your issue?

**Comment by bijeebuss** [comment]
No but you can close as this seems to be only affecting me. I have a local copy of typeorm linked so if I find a bug I'll just do a PR.

**Comment by pleerock** [comment]
okay, nice
