### ISSUE TITLE
Error not precise enough

### ISSUE THREAD

**Issue by amehmeto** [typeorm/typeorm#8399]
I've done some refactoring on my entities recently, and consequently, my code is breaking. My end-to-end and integration testing in particular.

I solved the integration test. As I have divided one big entity with two, I now have a OneToOne relationship between them. So I have to adapt the way I am seeding my database for testing.

The problem is that I cannot find where in my code and the error message isn't very talkative. Do you have any idea how I could solve this?

```
[Nest] 5596   - 22/11/2021, 19:58:41   [ExceptionHandler] Unable to connect to the database. Retrying (1)...
TypeORMError: Entity metadata for Athlete#biometrics was not found. Check if you specified a correct entity object and if it's connected in the connection options.
    at new TypeORMError (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/error/TypeORMError.ts:7:9)
    at /Users/arthurmehmetoglu/Development/CorpoSano/back/src/metadata-builder/EntityMetadataBuilder.ts:681:23
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.Object.<anonymous>.EntityMetadataBuilder.computeInverseProperties (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/metadata-builder/EntityMetadataBuilder.ts:676:34)
    at /Users/arthurmehmetoglu/Development/CorpoSano/back/src/metadata-builder/EntityMetadataBuilder.ts:119:56
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.Object.<anonymous>.EntityMetadataBuilder.build (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/metadata-builder/EntityMetadataBuilder.ts:119:25)
    at ConnectionMetadataBuilder.Object.<anonymous>.ConnectionMetadataBuilder.buildEntityMetadatas (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/connection/ConnectionMetadataBuilder.ts:65:111)
    at Connection.Object.<anonymous>.Connection.buildMetadatas (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/connection/Connection.ts:510:59)
    at Connection.<anonymous> (/Users/arthurmehmetoglu/Development/CorpoSano/back/src/connection/Connection.ts:186:18)
```

**Comment by spotykatch** [comment]
Seems like typeorm can't find `Biometrics` entity. Can be coursed by `@Entity()` decorator missing or wrong `enities` param in `ormconfig.json` or typo in the name of entity file.

**Comment by amehmeto** [comment]
It's probably none of that as I am using NestJs and those are generated automatically.
Moreover, I fixed this issue on my integration test by fixing the fixture.

Here is some more code:

`athlete.entity.ts`
```
import { Column, Entity, JoinColumn, OneToOne } from 'typeorm'
import { Base } from '../../__infrastructure__/typeorm/base.entity'
import { Biometrics } from '../../biometrics/entities/biometrics.entity'

@Entity()
export class Athlete extends Base {
  @Column()
  name: string

  @Column({ unique: true })
  email: string

  @Column()
  password: string

  @OneToOne(() => Biometrics)
  @JoinColumn()
  biometrics: Biometrics

  constructor(partial: Partial<Athlete> = {}) {
    super()
    Object.assign(this, partial)
  }
}
```



`biometrics.entity.ts`
```
import { Column, Entity } from 'typeorm'
import { Gender } from '../types/gender.enum'
import { UnitSystem } from '../types/metric-system.enum'
import { WeightGoal } from '../types/weight-goal.enum'
import { Base } from '../../__infrastructure__/typeorm/base.entity'

@Entity()
export class Biometrics extends Base {
  @Column()
  height: number

  @Column()
  lengthUnit: UnitSystem

  @Column()
  weight: number

  @Column()
  weightUnit: UnitSystem

  @Column({ nullable: true })
  bodyFat: number

  @Column()
  gender: Gender

  @Column()
  birthday: Date

  @Column()
  weightGoal: WeightGoal

  constructor(partial: Partial<Biometrics> = {}) {
    super()
    Object.assign(this, partial)
  }
}
```


`app.e2e-spec.ts`
```
describe('AppController (e2e)', () => {
  let app: INestApplication
  let connection: Connection
  let token: AccessToken

  function expectGqlEndpoint(
    query: Query,
    expectedData: Record<string, unknown> | Array<Record<string, unknown>>,
    isAuthenticated: boolean = true,
  ) {
    const tokenJwt = isAuthenticated ? token.token : undefined
    const GRAPHQL_URL = '/graphql'
    const dataKey = getDataKey(query)

    return request(app.getHttpServer())
      .post(GRAPHQL_URL)
      .set('Authorization', 'Bearer ' + tokenJwt)
      .send(query)
      .expect((response: any) =>
        handleGraphQLResponse(response, dataKey, expectedData),
      )
  }

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile()

    app = moduleFixture.createNestApplication()
    await app.init()

    connection = app.get(Connection)
    await generateFixtures(connection)
    token = await generateJwtToken(app, token)
  })
    test('Get Athlete', () => {
      const getAthleteQuery = {
        query: `query GetAthlete($athleteId: ID!) {
          getAthlete(athleteId: $athleteId) {
            id
            name
            biometrics {
              height
              weight
              bodyFat
            }
          }
        }`,
        variables: {
          athleteId: athleteFixture.id,
        },
      }
      const expectedAthlete = {
        id: athleteFixture.id,
        name: athleteFixture.name,
      }

      return expectGqlEndpoint(getAthleteQuery, expectedAthlete)
    })
})
```

`generate-fixtures.ts`
```
import { Connection } from 'typeorm'
import { athleteDataBuilder } from '../data-builders/athlete.data-builder'
import { workoutDataBuilder } from '../data-builders/workout.data-builder'
import { exerciseDataBuilder } from '../data-builders/exercise.data-builder'
import { exerciseTemplateDataBuilder } from '../data-builders/exercise-template.data-builder'
import { programDataBuilder } from '../data-builders/program.data-builder'
import { TypeOrmExerciseRepository } from '../../src/exercise/repositories/type-orm-exercise.repository'
import { TypeOrmWorkoutRepository } from '../../src/workout/repositories/typeorm-workout.repository'
import { TypeOrmProgramRepository } from '../../src/program/repositories/type-orm-program.repository'
import { TypeOrmAthleteRepository } from '../../src/athlete/repositories/typeorm-athlete.repository'
import * as Faker from 'faker'
import { TypeOrmExerciseTemplateRepository } from '../../src/exercise/repositories/type-orm-exercise-template.repository'
import { ExerciseTemplate } from '../../src/exercise/entities/exercise-template.entity'
import { biometricsDataBuilder } from '../data-builders/biometrics.data-builder'
import { TypeOrmBiometricsRepository } from '../../src/biometrics/repositories/typeorm-biometrics.repository'

export const programFixture = programDataBuilder()
export const workoutFixture = workoutDataBuilder()
export const exercisesFixture = [
  exerciseDataBuilder({
    position: 0,
    createdAt: Faker.date.past(30),
    deletedAt: null as Date,
    template: exerciseTemplateDataBuilder(),
  }),
  exerciseDataBuilder({
    position: 1,
    createdAt: Faker.date.past(0),
    template: exerciseTemplateDataBuilder(),
  }),
]
export const biometricsFixture = biometricsDataBuilder()
export const athleteFixture = athleteDataBuilder({
  biometrics: biometricsDataBuilder(),
})
export const exercisesTemplatesFixture = [
  {
    id: '00000000-0000-0000-0000-000000000000',
    title: 'Jumping jacks',
  },
  {
    id: '00000000-0000-0000-0000-000000000001',
    title: 'Wall sit',
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    title: 'Push-up',
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    title: 'Abdominal crunch',
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    title: 'Squat',
  },
  {
    id: '00000000-0000-0000-0000-000000000005',
    title: 'Triceps dip on chair',
  },
  {
    id: '00000000-0000-0000-0000-000000000006',
    title: 'Plank',
  },
  {
    id: '00000000-0000-0000-0000-000000000007',
    title: 'High knees running in place',
  },
  {
    id: '00000000-0000-0000-0000-000000000008',
    title: 'Lunge',
  },
  {
    id: '00000000-0000-0000-0000-000000000009',
    title: 'Push-up and rotation',
  },
  {
    id: '00000000-0000-0000-0000-000000000010',
    title: 'Side plank',
  },
  {
    id: '00000000-0000-0000-0000-000000000011',
    title: 'Jumping Rope',
  },
].map((exercise) => new ExerciseTemplate(exercise))

async function saveFixtures(
  connection: Connection,
  entityRepoFixturePair: any,
) {
  const [repository, fixture] = entityRepoFixturePair
  const customRepository = connection.getCustomRepository(repository)
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  await customRepository.save(fixture)
}

export async function generateFixtures(connection: Connection) {
  const workouts = [
    {
      ...workoutFixture,
      exercises: exercisesFixture,
    },
  ]
  const program = {
    ...programFixture,
    workouts,
  }
  const athlete = {
    ...athleteFixture,
    biometrics: biometricsFixture,
  }

  const entityRepositoryFixturePairs = [
    [TypeOrmExerciseTemplateRepository, exercisesTemplatesFixture],
    [TypeOrmExerciseRepository, exercisesFixture],
    [TypeOrmWorkoutRepository, workouts],
    [TypeOrmProgramRepository, program],
    [TypeOrmBiometricsRepository, biometricsFixture],
    [TypeOrmAthleteRepository, athlete],
  ]

  for (const pair of entityRepositoryFixturePairs)
    await saveFixtures(connection, pair)
}
```

**Comment by amehmeto** [comment]
This is what I had to change in my integration test to make it work. The error message was the same:

From

```

const athleteFixture = new Athlete(athleteDataBuilder())

describe('TypeOrmAthleteRepository', () => {
  let athleteRepository: TypeOrmAthleteRepository

  beforeAll(async () => {
    const module = await Test.createTestingModule({
      imports: [
        TypeOrmModule.forRoot(config.db),
        TypeOrmModule.forFeature([TypeOrmAthleteRepository]),
      ],
    }).compile()

    athleteRepository = module.get<TypeOrmAthleteRepository>(
      getRepositoryToken(TypeOrmAthleteRepository),
    )

    await athleteRepository.save(athleteFixture)
  })
  ```
  
  To
  
  ```
  describe('TypeOrmAthleteRepository', () => {
  let athleteRepository: TypeOrmAthleteRepository
  let biometricsRepository: TypeOrmBiometricsRepository

  beforeAll(async () => {
    const module = await Test.createTestingModule({
      imports: [
        TypeOrmModule.forRoot(config.db),
        TypeOrmModule.forFeature([
          TypeOrmAthleteRepository,
          TypeOrmBiometricsRepository,
        ]),
      ],
    }).compile()

    athleteRepository = module.get<TypeOrmAthleteRepository>(
      getRepositoryToken(TypeOrmAthleteRepository),
    )
    biometricsRepository = module.get<TypeOrmBiometricsRepository>(
      getRepositoryToken(TypeOrmBiometricsRepository),
    )

    const biometrics = await biometricsRepository.save(biometricsFixture)
    const athlete = {
      ...athleteFixture,
      biometrics,
    }
    await athleteRepository.save(athlete)
  })
  ```

What's really annoying is how everything crash before being able to run anything. I can't even do basic `console.log()` to try to understand what's going on and where there is a problem.

**Comment by mettini** [comment]
For future devs getting stuck on this: I ran into a weird issue with my Webpack build version (though dev environment was all good). Turns out the minifier was playing tricks, giving the same key to different class names. This StackOverflow saved my day: https://stackoverflow.com/questions/68042707/getting-error-when-i-save-an-entity-error-cyclic-dependency-e-aws-serv/69824517#69824517

**Comment by bilalouqda** [comment]
Guys i have same err  how i can fix it 
[Nest] 17596  - 03/20/2024, 10:33:36 AM   ERROR [ExceptionHandler] Entity metadata for T2s$Depenses#category was not found. Check if you specified a 
correct entity object and if it's connected in the connection options.
TypeORMError: Entity metadata for T2s$Depenses#category was not found. Check if you specified a correct entity object and if it's connected in the connection options.

**Comment by andrewhessler** [comment]
I had this issue running integration tests with Jest tests. The import in the entity for the relation...
```ts
import { Column, Entity, JoinColumn, OneToOne } from 'typeorm'
import { Base } from '../../__infrastructure__/typeorm/base.entity'
import { Biometrics } from '../../biometrics/entities/biometrics.entity' // Here's the import that matters

@Entity()
export class Athlete extends Base {
  @Column()
  name: string

  @Column({ unique: true })
  email: string

  @Column()
  password: string

  @OneToOne(() => Biometrics)
  @JoinColumn()
  biometrics: Biometrics

  constructor(partial: Partial<Athlete> = {}) {
    super()
    Object.assign(this, partial)
  }
}
```

had to have the same relative path as the import in the integration test:

```ts
import { Biometrics } from '../../biometrics/entities/biometrics.entity' // this works
import { Biometrics } from '../../biometrics/entities/' // this fails even though it may be a valid path with a re-export from an index
```

Still not sure on the why, but I know it messes with the type callback passed to the relational decorators like `OneToOne` when building the entityMetadata.

**Comment by mysql-x-devapi9** [comment]
> I had this issue running integration tests with Jest. The import in the entity for the relation...
> 
> import { Column, Entity, JoinColumn, OneToOne } from 'typeorm'
> import { Base } from '../../__infrastructure__/typeorm/base.entity'
> import { Biometrics } from '../../biometrics/entities/biometrics.entity' // Here's the import that matters
> 
> @Entity()
> export class Athlete extends Base {
>   @Column()
>   name: string
> 
>   @Column({ unique: true })
>   email: string
> 
>   @Column()
>   password: string
> 
>   @OneToOne(() => Biometrics)
>   @JoinColumn()
>   biometrics: Biometrics
> 
>   constructor(partial: Partial<Athlete> = {}) {
>     super()
>     Object.assign(this, partial)
>   }
> }
> had to have the same relative entrypoint as the import in the integration test:
> 
> import { Biometrics } from '../../biometrics/entities/biometrics.entity' // this works
> import { Biometrics } from '../../biometrics/entities/' // this fails even though it may be a valid path with a re-export from an index, this would be valid if the OneToOne callback was also imported from the index in the entity above
> Still not sure on the why, but I know it messes with the type callback passed to the relational decorators like `OneToOne` when building the entityMetadata.
> 
> An alternative workaround was to pass the string representation of the relation type, so in this case
> 
>   // @OneToOne(() => Biometrics)
>   @OneToOne('Biometrics')
>   @JoinColumn()
>   biometrics: Biometrics





https://nodeer.space/questions/saving-data-from-a-one-to-one-relationship-using-typeorm-and-nestjs-in-a-socalled-way-is-a-breeze-heres-how-you
