### ISSUE TITLE
Generating migrations with cli

### ISSUE THREAD

**Issue by SleeveShirtholes** [typeorm/typeorm#8810]
### Expected Behavior

Migrations get generated using the cli

### Actual Behavior

I am following the documentation outlined here https://typeorm.io/migrations and I feel like the documentation is way different then what is actually happening in the cli. I have tried just running the following command:

`typeorm migration:generate -n PostRefactoring`

When I run this command I get the following:

`Not enough non-option arguments: got 0, need at least 1`

So then I modify the command to something like this:

`Missing required argument: dataSource`

So then from there I add the datasource since that is what it is asking for:

`npx typeorm migration:generate test -d app-data-source.ts` (I found the -d somewhere online  while investigating this issue)

But once I run that command I get the following error:

`File must contain a TypeScript / JavaScript code and export a DataSource instance.`

I have been trying to get this to work for days and I am about ready to throw the towl in and use a different ORM...which I don't want to do. I know that everything is working fine because I can start up the app and the app connects to the database and creates rows in the database. So it is just something with the cli and trying to generate the migrations.

Here is what is in my app-data-source.ts file:

```
import { DataSource } from "typeorm";
import { User } from "./entitiy/User";

const myDataSource = new DataSource({
  type: "postgres",
  host: "localhost",
  port: 5432,
  username: "postgres",
  password: "",
  database: "postgres",
  entities: [User],
  migrations: ["/migrations/"],
  logging: true,
  synchronize: true,
});


export default myDataSource;
```

This is the contents of my app.ts file:

```
import * as express from "express";
import { Request, Response } from "express";
import myDataSource from "./app-data-source";
import { User } from "./entitiy/User";

// establish database connection
myDataSource
  .initialize()
  .then(() => {
    console.log("Data Source has been initialized!");
  })
  .catch((err) => {
    console.error("Error during Data Source initialization:", err);
  });

// create and setup express app
const app = express();
app.use(express.json());

// register routes
app.get("/users", async function (req: Request, res: Response) {
  const users = await myDataSource.getRepository(User).find();
  res.json(users);
});

app.get("/users/:id", async function (req: Request, res: Response) {
  const results = await myDataSource.getRepository(User).findOneBy({
    id: +req.params.id,
  });
  return res.send(results);
});

app.post("/users", async function (req: Request, res: Response) {
  const user = await myDataSource.getRepository(User).create(req.body);
  const results = await myDataSource.getRepository(User).save(user);
  return res.send(results);
});

app.put("/users/:id", async function (req: Request, res: Response) {
  const user = await myDataSource.getRepository(User).findOneBy({
    id: +req.params.id,
  });
  myDataSource.getRepository(User).merge(user, req.body);
  const results = await myDataSource.getRepository(User).save(user);
  return res.send(results);
});

app.delete("/users/:id", async function (req: Request, res: Response) {
  const results = await myDataSource.getRepository(User).delete(req.params.id);
  return res.send(results);
});

// start express server
app.listen(3000);
```

All these files were setup using the instructions outlined in the express typeorm documentation:
[Example with Express](https://typeorm.io/example-with-express)

Which BTW, this also has issues and doesn't run from what is outlined in the directions. I had to make some modifications to actually make the app run compared to what is outlined in that guide. One of the changes I made in the data source file was putting the actual Entity name in the entity property of the datasource compared to the guide that has you put the path in.

Anyway, am I crazy...am I doing something wrong? You guys might not have enough information to answer the first question but can you at least help with trying to figure out how to make the migrations work?

### Steps to Reproduce

Set up you app using the guide outlined above to use express

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  MAC OS Monterrey         |
| Node.js version     | v16.14.2  | 
| Typescript version  | 4.5.2  | 
| TypeORM version     | 0.3.4  | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | yes            |
| `react-native`    | no            |
| `sap`             | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by Sreejith288** [comment]
+ @pleerock

**Comment by anoutsider** [comment]
Had the same issue, the workaround I found for now is to use the compiled js file

For example

`npx typeorm migration:generate test -d dist/app-data-source.js`

As the cli command fails to import the .ts file for some reason, probably because of the file url it tries to generate, also for some reason it will only import a ts file if the closest package.json file is set to a type => module

File URL -> https://github.com/typeorm/typeorm/blob/eacecce4a6eedd327dc59e1d3a3114c67ebfdf5b/src/util/ImportUtils.ts#L15

package.json module type check -> https://github.com/typeorm/typeorm/blob/eacecce4a6eedd327dc59e1d3a3114c67ebfdf5b/src/util/ImportUtils.ts#L32

**Comment by matthewdowns** [comment]
How did 0.3.0 get past the testing phase when the CLI is completely broken?

**Comment by AashJ** [comment]
+1, pretty unusable atm, will switch off for my newer projects

**Comment by matthewdowns** [comment]
@AashJ came up with a really dumb way of doing the "schema:log" command (can be applied to any other command too) without having to create a separate dataSource.js file. This script will use your dataSource.ts file.

Assuming you have a file named _dataSource.ts_ located under your _src_ folder, and looks like this:
```ts
import { resolve } from 'path'
import { DataSource } from 'typeorm'

const dataSource = new DataSource({
  type: process.env.TYPEORM_TYPE as any,
  host: process.env.TYPEORM_HOST,
  port: parseInt(process.env.TYPEORM_PORT),
  username: process.env.TYPEORM_USERNAME,
  password: process.env.TYPEORM_PASSWORD,
  database: process.env.TYPEORM_DATABASE,
  entities: [resolve(__dirname, './orm/**/*.entity.js')],
  migrations: [resolve(__dirname, './orm/**/*.migration.js')],
  subscribers: [resolve(__dirname, './orm/**/*.subscriber.js')]
})

// this line is needed for 
module.exports.DataSource = dataSource

export default dataSource
```

Then you can have a script that does this:
_./scripts/typeorm/schema:log.ts_
```ts
import { execSync } from 'child_process'
import { readFileSync, rmSync, writeFileSync } from 'fs'
import path from 'path'

const dataSourceTsPath = path.resolve(__dirname, '../../src/dataSource.ts')
const dataSourceJsPath = path.resolve(__dirname, 'dataSource.js')

const tscCommand = `tsc --outDir ${__dirname} --target ESNext --module commonjs --moduleResolution node ${dataSourceTsPath}`
const schemaLogCommand = `npx typeorm --dataSource ${dataSourceJsPath} schema:sync`

try {
  console.log('Compiling dataSource.ts to CommonJS')
  execSync(tscCommand)
  const dataSourceJs = readFileSync(dataSourceJsPath)
    .toString('utf-8')
    // replace the default export with "module.exports.DataSource", which is what's required by typeorm
    .replace('exports.default = dataSource;', 'module.exports.DataSource = dataSource;')
  // remove the old dataSource.js file
  rmSync(dataSourceJsPath)
  // write the new dataSource.js file
  writeFileSync(dataSourceJsPath, dataSourceJs)

  console.log('Executing TypeORM schema:log command')
  const schemaLog = execSync(schemaLogCommand).toString('utf-8')
  console.log(schemaLog)
} catch (e) {
  console.error(e)
} finally {
  console.log('Removing dataSource.js')
  rmSync(dataSourceJsPath)
}
```

This is super hacky, and I absolutely hate myself for writing this garbage.

**Comment by evskorobogatij** [comment]
I have the same issue

**Comment by evskorobogatij** [comment]
> Had the same issue, the workaround I found for now is to use the compiled js file
> 
> For example
> 
> `npx typeorm migration:generate test -d dist/app-data-source.js`
> 
> As the cli command fails to import the .ts file for some reason, probably because of the file url it tries to generate, also for some reason it will only import a ts file if the closest package.json file is set to a type => module
> 
> File URL ->
> 
> https://github.com/typeorm/typeorm/blob/eacecce4a6eedd327dc59e1d3a3114c67ebfdf5b/src/util/ImportUtils.ts#L15
> 
> package.json module type check ->
> 
> https://github.com/typeorm/typeorm/blob/eacecce4a6eedd327dc59e1d3a3114c67ebfdf5b/src/util/ImportUtils.ts#L32

This is not work

`
npx typeorm migration:generate -d .\dist\db\ormconfig.js Init
`

And I have the same issue

**Comment by msalsbery** [comment]
I haven't found any way to get this to work either.

On a related note:  If cli: {...} is no longer a member of BaseDataSourceOptions or its descendants, how does the CLI know where my entities/migrations/subscriptions are located? I don't see any command line options in the CLI help...

**Comment by msalsbery** [comment]
Thanks to @pleerock and [this post](https://github.com/typeorm/typeorm/issues/8814#issuecomment-1080945772) I now have migration creation/generation working.

The CLI now requires the full path to the output file, so if you have an npm script like
```
    "typeorm": "typeorm-ts-node-esm -d ./config/data-source.ts"
```
then an example call to that script to generate a migration could look something like
```
npm run typeorm -- migration:generate ./src/database/migrations/my-migration-name
```
@pleerock  thank you for that!

**Comment by SleeveShirtholes** [comment]
I also got the migrations to work but only by compiling my code and using .js data-source file. I still can't get the migrations to work using the .ts files. I also can't get the entities path in the data-source file to work and have to declare each entity.

**Comment by kylevillegas93** [comment]
@SleeveShirtholes  many want to try: ```['dist/src/entities/**/*{.js,.ts}']```

**Comment by msalsbery** [comment]
> I also got the migrations to work but only by compiling my code and using .js data-source file. I still can't get the migrations to work using the .ts files. I also can't get the entities path in the data-source file to work and have to declare each entity.

@SleeveShirtholes  In my example I'm using all TS. In addition to @kylevillegas93 's reply, my data-source.ts looks like
```typescript
import { DataSource } from 'typeorm';
import { SqlServerConnectionOptions } from 'typeorm/driver/sqlserver/SqlServerConnectionOptions';
// eslint-disable-next-line node/no-missing-import
import { CustomNamingStrategy } from '../src/database/models/naming-strategy';

const options: SqlServerConnectionOptions = {
  type: 'mssql',
  url: '',
  host: 'localhost',
  port: 1433,
  dropSchema: false,
  synchronize: false,
  extra: {
    trustServerCertificate: true
  },
  options: {
    useUTC: true,
    abortTransactionOnError: true, // SET XACT_ABORT ON|OFF
    enableArithAbort: true
  },
  username: '...',
  password: '...',
  database: '...',
  logging: false, // TypeORM true, false, ['query', 'error', 'schema', 'warn', 'info', 'log']
  logger: 'advanced-console', // TypeORM 'advanced-console' (default), 'simple-console', 'file'
  entities: ['src/database/models/**/*.ts'],
  migrations: ['src/database/migrations/**/*.ts'],
  subscribers: ['src/database/subscribers/**/*.ts'],
  namingStrategy: new CustomNamingStrategy()
};

export default new DataSource(options);
```
Hope that helps in some way...

**Comment by SleeveShirtholes** [comment]
@msalsbery @kylevillegas93 

So I just tried both suggestions and still can't get migrations to work with the .ts file. Here is my .ts file:

```
import { DataSource } from "typeorm";
import { PostgresConnectionOptions } from "typeorm/driver/postgres/PostgresConnectionOptions";

const options: PostgresConnectionOptions = {
  type: "postgres",
  host: process.env.PGHOST,
  port: 5432,
  username: process.env.PGUSER,
  password: process.env.PGPASSWORD,
  database: process.env.PGDATABASE,
  entities: ["src/**/entities/*{.js,.ts}"],
  // entities: [
  //   BudgetAppUser,
  //   Account,
  //   UserAccount,
  //   Biller,
  //   AccountBiller,
  //   AccountBill,
  //   Frequency,
  //   BillerType,
  // ],
  migrations: ["./build/**/migrations/**.js"],
  synchronize: false,
  logging: false,
};

export default new DataSource(options);
```

Here is my package.json file:
```
{
  "name": "back_end",
  "version": "1.0.0",
  "description": "",
  "main": "index.ts",
  "scripts": {
    "start": "nodemon src/index.ts",
    "typeorm": "typeorm-ts-node-esm -d ./src/data-source.ts"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.19.2",
    "express": "^4.17.3",
    "pg": "^8.7.3",
    "reflect-metadata": "^0.1.13",
    "typeorm": "^0.3.3",
    "typescript": "^4.6.2"
  },
  "devDependencies": {
    "@types/express": "^4.17.13",
    "@types/node": "^17.0.21",
    "nodemon": "^2.0.15",
    "ts-node": "^10.7.0"
  }
}
```

The error I am getting now is:
`sh: typeorm-ts-node-esm: not found`

I was getting this error before:
`File must contain a TypeScript / JavaScript code and export a DataSource instance.`

But I think the reason I am getting that error is because I didn't originally have the typeorm script in my package.json.

**Comment by msalsbery** [comment]
@SleeveShirtholes  here's my relevant package.json stuff... typeorm version is different than yours I noticed...
```json
{
  "dependencies": {
    "mssql": "^8.0.2",
    "reflect-metadata": "^0.1.13",
    "typeorm": "^0.3.4"
  },
  "devDependencies": {
    "@types/node": "^17.0.23",
    "@types/tedious": "^4.0.7",
    "ts-node": "10.7.0",
    "typescript": "^4.6.2"
  },
  "scripts": {
    "typeorm": "typeorm-ts-node-esm -d ./config/data-source.ts"
  }
}
```

**Comment by SleeveShirtholes** [comment]
@msalsbery I am getting this error now when running the following command:

Error:
`env: can't execute 'node --require ts-node/register': No such file or directory`

Command:
`npm run typeorm -- migration:generate ./src/budget_app/migrations/initialMigration`

Do you know why that is? Sorry to keep bugging you.

**Comment by msalsbery** [comment]
@SleeveShirtholes  are you sure all dependencies are updated to latest versions and installed? That looks like it's not seeing ts-node

**Comment by msalsbery** [comment]
@SleeveShirtholes  hmm, I got nothin ;)   If you added the typeorm script to package.json and that script runs typeorm-ts-node-esm then the only difference from what I'm doing is I'm not running in a container

**Comment by SleeveShirtholes** [comment]
@msalsbery Ok...it does look like its the container that is the issue. I ran the command outside the container and everything worked fine. Thanks for your help!

**Comment by ricardo85x** [comment]
I could not make the run command work

Here is my files:

## ./src/database/data_source.ts
```js
import { DataSource } from "typeorm";

const AppDataSource = new DataSource({
  type: process.env.DB_TYPE,
  host: process.env.DB_HOST,
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  port: process.env.DB_PORT,
  entities: [],
  migrations: ["./src/database/migrations/*.ts"],
});

export default AppDataSource;

AppDataSource.initialize()
  .then(() => console.log("Data Source has been initialized"))
  .catch((error) => console.error("Error initializing Data Source", error));
```

## ./src/database/migrations/1648475278557-CreateCategories.ts
```js
import { MigrationInterface, QueryRunner, Table } from "typeorm";

export class CreateCategories1648475278557 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: "categories",
        columns: [
          {
            name: "id",
            type: "uuid",
            isPrimary: true,
          },
          {
            name: "name",
            type: "varchar",
          },
        ],
      })
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable("categories");
  }
}

```

## Command I' using to run the migration

```sh
yarn typeorm-ts-node-esm -d ./src/database/data_source.ts migration:run
```

I always got the error:

```
Error during migration run:
Error: Invalid file path given: "/Users/myusername/Documents/code/backend/nodejs/typeorm-project/src/database/data_source.ts". File must contain a TypeScript / JavaScript code and export a DataSource instance.
```

**Comment by MrPostie** [comment]
For me the following is working:

`package.json`
```json
...
"scripts": {
 ...
  "typeorm": "node --require ts-node/register ./node_modules/typeorm/cli.js"
}
```

I use a `ormconfig.ts` in the root of the project:
```typescript
import { DataSource } from 'typeorm';
import configuration from './src/config/configuration';

configuration();

const devDataSource = new DataSource({
  type: 'mariadb',
  host: 'localhost',
  port: 3306,
  username: 'user',
  password: 'password',
  database: 'database',
  entities: ['**/*.entity.js'],
  synchronize: false,
  migrations: ['src/migrations/*.js'],
});

export default devDataSource;
```

Then I run the migrations with `yarn typeorm migration:run -d ormconfig.ts` and that works.

Maybe this works for others too.

My problem however is that the `ormconfig.ts` doesn't use `process.env.HOSTNAME` from the `.env` file in the root.

**Comment by myflowpl** [comment]
I'v just tried all examples here with no success

still getting `Error: Invalid file path given: "C:\Users\username\nest-server\orm.ts". File must contain a TypeScript / JavaScript code and export a DataSource instance.` error`

and this file is present, tried with .js files, but no success, tried ts-node, typeorm-ts-node-commonjs, typeorm-ts-node-esm and every where got the same error

**Comment by myflowpl** [comment]
> I'v just tried all examples here with no success
> 
> still getting `Error: Invalid file path given: "C:\Users\username\nest-server\orm.ts". File must contain a TypeScript / JavaScript code and export a DataSource instance.` error`
> 
> and this file is present, tried with .js files, but no success, tried ts-node, typeorm-ts-node-commonjs, typeorm-ts-node-esm and every where got the same error

I found the problem 🎉

It looks like @MrPostie solution is working, in my case there was problem with my ormconfig.ts, I used old options for `cli` and it's not present in `0.3` version, and the problem is ts-node did not print the compilation error, it only shows that the file is missing. After I run `npm run start:dev` I noticed the ts compilation error, I fixed it, run the `npm run typeorm migration:run` command nad it's working. here are my files:

package.json
```
"scripts": {
  "typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js -d ormconfig.ts"
}
```
ormconfig.ts
```typescript
import { DataSource } from 'typeorm';

const source = new DataSource({
  "type": "sqlite",
  "database": "./storage/nest.db",
  "entities": ["src/**/*.entity.ts"],
  "migrationsTableName": "migrations",
  "migrations": ["src/db/migrations/*.ts"],
});

export default source;
```
command 
```
npm run typeorm migration:run
```

it also works with this package.json 
```
"scripts": {
  "typeorm": "typeorm-ts-node-commonjs -d ormconfig.ts"
}
```

Thanks 💪

**Comment by ricardo85x** [comment]
[MrPostie](https://github.com/MrPostie)
Actually the only problem was the file with the Datasouce export that can't read the .env file

then this command:
```
yarn typeorm-ts-node-commonjs migration:run -d src/database/data_source.ts
```

works normally IF it is NOT using the .env variables

Now we need to figure out how make this file read the .env variables

**Comment by myflowpl** [comment]
Yes, you have to use `dotenv` or `@nestjs/config` witch is using dotenv internally.

OK, i had some other issue, some of the commands don't work, for example `migration:create`, what I found is that `dataSource` option `-d` is required in one command and breaks others, so you can't do general configuration like with `typeorm v0.2`

so my final working code is like this:


`/src/db/ormconfig.ts`

```typescript
import { DataSource } from 'typeorm';
import { SqliteConnectionOptions } from 'typeorm/driver/sqlite/SqliteConnectionOptions';

const source = new DataSource({
  "type": "sqlite",
  "database": "./storage/nest.db",
  "entities": ["src/**/*.entity.ts"],
  "migrationsTableName": "migrations",
  "migrations": ["src/db/migrations/*.ts"],
});

export default source;
```

`package.json`

```json
{
  "scripts": {
    "typeorm": "typeorm-ts-node-commonjs -d ./src/db/ormconfig.ts",
    "migration:generate": "npm run typeorm migration:generate",
    "migration:show": "npm run typeorm migration:show",
    "migration:run": "npm run typeorm migration:run",
    "migration:revert": "npm run typeorm migration:revert",
    "migration:create": "typeorm-ts-node-commonjs migration:create"
  }
}
```

In your terminal use it like this:

```bash
npm run migration:generate src/db/migrations/init-photos

npm run migration:create src/db/migrations/update-photos-data

npm run migration:show

npm run migration:run

npm run migration:revert
```

**Comment by myflowpl** [comment]
> @myflowpl How does migration:run work without -d option? How does cli find the migration? Do you have an ormconfig file still that it’s picking up using deprecated behavior?
> 
> I’m just curious, as I wouldn’t think it should work without specifying a DataSource and I’d want to make sure my cli and app runs are always using the same DataSource…
> 
> edit: Also, I use -d option on all cli commands without issue, so I’m curious why that doesn’t work for you

@msalsbery note that I did npm script called `typeorm` where i defined data source `-d` option, then i use it in other commands like `npm run typeorm migration:generate` so I'm not using pure typeorm cli command, but one configured by me. Then when I have to use command without `-d` option i use directly the official cli, for example: `typeorm-ts-node-commonjs migration:create`.

My goal is to have predefined npm scripts so my team doesn't have to remember any extra options, they just give simple command to generate the migration and run it, and me as a one who knows how  configurations works, I prepare the scripts.

That interesting it works for you with the `-d` option for all commands, may be it works whey you use cli directly without npm scripts, I wasted lots of time to make it working, and now it works so I'm going to leave it like it is without further investigation

**Comment by msalsbery** [comment]
@myflowpl  I reread and noticed it was only the create that didn’t use -d and realized that operation wouldn’t need the database so that’s why it works. Sorry for the confusion and thank you for setting my head right!

**Comment by akindo** [comment]
Using TypeScript datasource and migration files, e. g.
`"typeorm": "typeorm-ts-node-commonjs -d src/db/dataSource.ts"`
`"migration:run": "npm run typeorm migration:run",`
doens't work in Docker containers because of [this](https://github.com/typeorm/typeorm/pull/8821). [More info](https://github.com/typeorm/typeorm/issues/8818).

Until the fix is released, use transpiled-to-JS datasource and migration files:
`"typeorm": "node --require ts-node/register ./node_modules/typeorm/cli.js -d dist/src/db/dataSource.js",`
`"migration:run": "npm run typeorm migration:run",`

**Comment by mokuteki225** [comment]
After countless attempts I finally managed to make it work, so here is my ormconfig.ts, it is situated inside of a root dir
```ts
import { DataSource } from 'typeorm';

const dataSource = new DataSource({
  type: 'postgres',
  host: 'localhost',
  port: 5432,
  username: 'postgres',
  password: 'pass123',
  database: 'postgres',
  entities: ['src/**/*.model.{js,ts}'],
  migrations: ['src/migrations/*.{js,ts}'],
});

export default dataSource;
``` 
My package.json typeorm script
```json
{
  "scripts": {
    "typeorm": "node --require ts-node/register ./node_modules/typeorm/cli.js"
  }
}
```
And finally the command to generate a migration
```bash
$ npm run typeorm -- migration:generate -d ormconfig.ts src/migrations/user-table
```
Also I'm using TypeORM version 0.3.5, hope this might help someone!

**Comment by hardboiled** [comment]
Has anyone tried running migrations after generating them?
I'm having an issue where `migration:show` and `migration:run` [are essentially no-ops](https://github.com/typeorm/typeorm/issues/8860#issuecomment-1097025797). 

I've used typeorm in previous projects and am trying to roll one with the latest and greatest. I can't figure out why the migrations aren't running after being successfully generated.

**Comment by juniorduff** [comment]
I fix this problem this way

![image](https://user-images.githubusercontent.com/23487781/164733466-f8099116-4777-475a-a3ca-5789cb48166c.png)
First we need to remove the option -d dist/datasource.js  in your script 

![image](https://user-images.githubusercontent.com/23487781/164733623-0c3b93e7-8fb7-46d3-9a17-e01eff823e3d.png)

then  you need to  do the command with entire path
![image](https://user-images.githubusercontent.com/23487781/164733784-67d696a1-2de8-49e5-877b-557be023a0d6.png)


![image](https://user-images.githubusercontent.com/23487781/164733830-594f40ea-1dcd-43ca-b412-e5523951e43f.png)

**Comment by thenaim** [comment]
ormconfig.ts:
```ts
import * as dotenv from 'dotenv';
import { cwd, env } from 'process';
import { DataSource } from 'typeorm';

dotenv.config();

export const dataSource = new DataSource({
  type: 'postgres',
  host: env.TYPEORM_HOST,
  port: parseInt(env.TYPEORM_PORT),
  username: env.TYPEORM_USER,
  password: env.TYPEORM_PASSWORD,
  database: env.TYPEORM_DB,
  entities: [cwd() + '/src/**/*.entity.ts'],
  migrations: [cwd() + '/src/migrations/*.ts'],
  migrationsTableName: 'migrations',
  synchronize: false,
  dropSchema: false,
});
```

package.json:
```json
"typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli -d ./src/config/ormconfig.ts",
"migration:create": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli migration:create ./src/migrations/$npm_config_name",
"migration:generate": "npm run typeorm -- migration:generate ./src/migrations/$npm_config_name",
"migration:run": "npm run typeorm -- migration:run",
"migration:revert": "npm run typeorm -- migration:revert",
"schema:sync": "npm run typeorm -- schema:sync"
```

Command to generate a migration/create

```bash
npm run migration:create --name=foo
npm run migration:generate --name=bar
```

**Comment by wahidrezgui** [comment]
I remove -n option and it was solved for me:
 Package.json:
`  "migration:generate": "npm run build && npm run typeorm migration:create --"`
command :
`npm run migration:generate -- ./src/db/migrationdescription`

**Comment by MuhametSmaili** [comment]
> ormconfig.ts:
> 
> ```ts
> import * as dotenv from 'dotenv';
> import { cwd, env } from 'process';
> import { DataSource } from 'typeorm';
> 
> dotenv.config();
> 
> export const dataSource = new DataSource({
>   type: 'postgres',
>   host: env.TYPEORM_HOST,
>   port: parseInt(env.TYPEORM_PORT),
>   username: env.TYPEORM_USER,
>   password: env.TYPEORM_PASSWORD,
>   database: env.TYPEORM_DB,
>   entities: [cwd() + '/src/**/*.entity.ts'],
>   migrations: [cwd() + '/src/migrations/*.ts'],
>   migrationsTableName: 'migrations',
>   synchronize: false,
>   dropSchema: false,
> });
> ```
> 
> package.json:
> 
> ```json
> "typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli -d ./src/config/ormconfig.ts",
> "migration:create": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli migration:create ./src/migrations/$npm_config_name",
> "migration:generate": "npm run typeorm -- migration:generate ./src/migrations/$npm_config_name",
> "migration:run": "npm run typeorm -- migration:run",
> "migration:revert": "npm run typeorm -- migration:revert",
> "schema:sync": "npm run typeorm -- schema:sync"
> ```
> 
> command to generate a migration/create
> 
> ```shell
> npm run migration:create --name=foo
> npm run migration:generate --name=bar
> ```

## It is not recommended to use ormconfig  👉 check [the changelog](https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md#:~:text=drop%20ormconfig%20support.%20ormconfig%20still%20works%20if%20you%20use%20deprecated%20methods%2C%20however%20we%20do%20not%20recommend%20using%20it%20anymore%2C%20because%20it%27s%20support%20will%20be%20completely%20dropped%20in%200.4.0.%20If%20you%20want%20to%20have%20your%20connection%20options%20defined%20in%20a%20separate%20file%2C%20you%20can%20still%20do%20it%20like%20this%3A)

**Comment by thenaim** [comment]
@MuhametSmaili, okey, what exactly am I doing wrong?

**Comment by MuhametSmaili** [comment]
> @MuhametSmaili, okey, what exactly am I doing wrong?

Sorry i wrote in the wrong library I thought I am in nest. Because earlier you could configure everything in the `ormconfig.ts` and they recognized the connection there. but if you check the link up in changelog, it reads that it won't work anymore the ormconfig they will drop in version 4.0. I do not know where you are using, but for example in nest, you will have to include in the app.module  [check this](https://docs.nestjs.com/techniques/database#:~:text=JS-,import%20%7B%20Module%20%7D%20from%20%27%40nestjs/common%27%3B%0Aimport%20%7B,)%2C%0A%20%20%5D%2C%0A%7D)%0Aexport%20class%20AppModule%20%7B%7D,-WARNING) or declare your factory and import with `useFactory`
But this is not related completely with this, and what you have done, because I thought I am in different place, sorry again.

**Comment by Lin-smg** [comment]
> Somewhere I read that the cli doesn't parse/read `.env` files. I've solved it using the `dotenv` package in the `ormconfig.ts`. Installed the package with `yarn install dotenv @types/dotenv -D`. Added `import 'dotenv/config';` at the top of the `ormconfig.ts` and now `process.env.XXX` can be used.

Thank you very much.
You save my time.

**Comment by depak379mandal** [comment]
Lost many hours due to this, it may be helpful others.

## ormconfig.ts file

```typescript
import { DataSource } from 'typeorm';
import load_entities from './src/modules/database/load_entities';
import * as dotenv from 'dotenv';
import { PostgresConnectionOptions } from 'typeorm/driver/postgres/PostgresConnectionOptions';

dotenv.config();

const configs: PostgresConnectionOptions = {
  type: process.env.DATABASE_TYPE as any,
  host: process.env.DATABASE_HOST,
  port: Number(process.env.DATABASE_PORT),
  username: process.env.DATABASE_USERNAME,
  password: process.env.DATABASE_PASSWORD,
  database: process.env.DATABASE_NAME,
  entities: load_entities,
  migrations: ['src/modules/database/migrations/*{.ts,.js}'],
};

export default new DataSource(configs);
```

## Scripts inside package.json

> In generate have to provide the path otherwise it is creating inside cwd/pwd

```json
{
    "typeorm": "typeorm-ts-node-commonjs -d ormconfig.ts",
    "migration:generate": "npm run typeorm migration:generate ./src/modules/database/migrations/$npm_config_name",
}```


## command to run

```bash
npm run migration:generate  --name=InitialMigration
```

**Comment by mateuseap** [comment]
After many hours trying, I finally made it work!

Firstly I created my `.env` file with my environment variables and then I created a `app.datasource.ts` file inside my project `src` directory (my `DataSource` is initialized inside my `main.ts`):

```typescript
import { DataSource } from 'typeorm';
import { ConfigService } from '@nestjs/config';
import { config } from 'dotenv';
import { Employee } from './employee/entities/employee.entity';
import { Position } from './position/entities/position.entity';
import { EmployeeToResearchArea } from './employee-to-research-area/entities/employee-to-research-area.entity';
import { EmployeeToRole } from './employee-to-role/entities/employee-to-role.entity';
import { Role } from './role/entities/role.entity';
import { ResearchArea } from './research-area/entities/research-area.entity';
import { database1663856426074 } from './database/migrations/1663856426074-database';

config();

const configService = new ConfigService();

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: configService.get('POSTGRES_HOST'),
  port: configService.get('POSTGRES_PORT'),
  username: configService.get('POSTGRES_USER'),
  password: configService.get('POSTGRES_PASSWORD'),
  database: configService.get('POSTGRES_DB'),
  synchronize: false,
  logging: false,
  entities: [
    Employee,
    Position,
    EmployeeToResearchArea,
    EmployeeToRole,
    Role,
    ResearchArea,
    EmployeeToResearchArea,
  ],
  migrations: [database1663856426074],
});
```

Then, I added the following scripts to my `package.json`:

```json
"scripts": {
  "typeorm": "ts-node ./node_modules/typeorm/cli",
  "typeorm:generate-migration:win": "npm run typeorm -- -d ./src/app.datasource.ts migration:generate ./src/database/migrations/%npm_config_name%",
  ...
}
```

After these two steps, I ran in my terminal the following command and everything worked well 😊

```script
npm run typeorm:generate-migration:win --name=migrationName
```

**Comment by Diluka** [comment]
Notice: not all commands recognize `-d --datasource` option

for example: for command `migration:create`
```sh
node -r tsconfig-paths/register -r ts-node/register ./node_modules/typeorm/cli.js -d ./ormconfig.ts migration:create test
```
will print
```log
cli.js migration:create <path>

Creates a new migration file.

Options:
  -h, --help       Show help                                           [boolean]
  -o, --outputJs   Generate a migration file on Javascript instead of Typescript
                                                      [boolean] [default: false]
  -t, --timestamp  Custom timestamp for the migration name
                                                       [number] [default: false]
  -v, --version    Show version number                                 [boolean]

Unknown argument: d
```

**Comment by ducdv98** [comment]
> Thanks to @pleerock and [this post](https://github.com/typeorm/typeorm/issues/8814#issuecomment-1080945772) I now have migration creation/generation working.
> 
> The CLI now requires the full path to the output file, so if you have an npm script like
> 
> ```
>     "typeorm": "typeorm-ts-node-esm -d ./config/data-source.ts"
> ```
> 
> then an example call to that script to generate a migration could look something like
> 
> ```
> npm run typeorm -- migration:generate ./src/database/migrations/my-migration-name
> ```
> 
> @pleerock thank you for that!

Perfect solution. Thank you!

**Comment by swport** [comment]
Seems like 0.3.11 have dropped support for -d option everybody's talking about in here. How in heaven's name do you specify where to look for data-source.ts now? Ah, what a wonderful first experience I had with typeorm.

**Comment by jeireff** [comment]
> Seems like 0.3.11 have dropped support for -d option everybody's talking about in this section
@swport  I'm using this Verion too. There is no problem with the -d parameter.

` "typeorm": "node --require ts-node/register ./node_modules/typeorm/cli.js",`
`"typeorm:migration:generate": "npm run typeorm migration:generate -- -d .\\data-source-default.ts",`
`"typeorm:migration:run": "npm run typeorm migration:run -- -d .\\data-source-default.ts",`
`"typeorm_like_in_the_docs_but_not_working_correctly": "typeorm-ts-node-commonjs"`
I'm using this commands (package.json) to run the generation and migration.

**Comment by greazleay** [comment]
> Seems like 0.3.11 have dropped support for -d option everybody's talking about in this section. How in heaven's name do you specify where to look for data-source.ts now? Ah, what a wonderful first experience I had with typeorm.

@swport , I am using this version too (0.3.11) and generating and running migrations works just fine with the -d option

**Comment by ullalaaron** [comment]
> 

You are the man!
Thank you!!

**Comment by toriqahmads** [comment]
same issue, the cli completely broken in @0.3.12 version

**Comment by msalsbery** [comment]
> same issue, the cli completely broken in @0.3.12 version

Completely still working for me...

https://github.com/typeorm/typeorm/blob/master/docs/using-cli.md

Are you using the -d option and pointing it to a file that exports a TypeORM DataSource?

**Comment by kkuk6-dev628** [comment]
`npx typeorm-ts-node-commonjs -d ormconfig.ts migration:generate path-to-migration`
This will work but following will show error 'Unknown argument: d'
`npx typeorm-ts-node-commonjs -d ormconfig.ts migration:create path-to-migration`

**Comment by JeremiahKoeiman** [comment]
I've tried pretty much everything, but it still doesn't work. I always get the following error:

`Error during migration run:
Error: Unable to open file: "dist\config\ormconfig.js". Cannot read properties of undefined (reading 'config')`

I don't think I've see anyone here having nestjs running in a docker container. Could this be the/an issue?

**Comment by saeidfiy** [comment]
> typeorm-ts-node-commonjs

if you ues typescript you should use like this

`npx typeorm-ts-node-esm -d ormconfig.ts migration:generate src/migrations/make-use
r-table`

**Comment by saeidfiy** [comment]
hi,
i use this method and work for me with typeorm v0.3.12

in ormconfig.ts i add : 
`import { TypeOrmModuleOptions } from '@nestjs/typeorm';
import { Admins } from './src/Entity/admins.entity';
import { DataSource } from 'typeorm';

import './src/dotenv-config';

export const ormConfig: TypeOrmModuleOptions = {
  type: 'postgres',
  url: process.env.DB_URL,
  synchronize: false,
  logging: true,
  entities: [Admins],
  migrations: ['./src/Migration/**/*{.ts,.js}'],
};

const cliConfig = new DataSource(ormConfig as any);

export default cliConfig;`

i use ormConfig for this:
`TypeOrmModule.forRoot(ormConfig)`

and run cli with 
`npx typeorm-ts-node-esm -d ormconfig.ts migration:generate src/migrations/make
-admins-table`

**Comment by Durisvk** [comment]
Should be fixed by the following: https://github.com/typeorm/typeorm/pull/10184

**Comment by dberardo-com** [comment]
i get this error when running just any one of the commnads above:

Error during migration generation:
TypeError: Cannot read properties of undefined (reading 'constructor')

seems to come from this file: 

```
  at ........\node_modules\typeorm\src\decorator\columns\Column.ts:202:32
    at __esDecorate (........\apps\users\src\db\models\user.entity.ts:14:40)
    at ........\apps\users\src\db\models\user.entity.ts:15:3
    at ........\apps\users\src\db\models\user.entity.ts:71:7
    at Object.<anonymous> (........\apps\users\src\db\models\user.entity.ts:73:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (........\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .ts] (........\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

any idea?

**Comment by ronan583** [comment]
> Lost many hours due to this, it may be helpful others.
> 
> ## ormconfig.ts file
> ```ts
> import { DataSource } from 'typeorm';
> import load_entities from './src/modules/database/load_entities';
> import * as dotenv from 'dotenv';
> import { PostgresConnectionOptions } from 'typeorm/driver/postgres/PostgresConnectionOptions';
> 
> dotenv.config();
> 
> const configs: PostgresConnectionOptions = {
>   type: 'postgres',
>   host: process.env.DATABASE_HOST,
>   port: Number(process.env.DATABASE_PORT),
>   username: process.env.DATABASE_USERNAME,
>   password: process.env.DATABASE_PASSWORD,
>   database: process.env.DATABASE_NAME,
>   entities: load_entities,
>   migrations: ['src/modules/database/migrations/*{.ts,.js}'],
> };
> 
> export default new DataSource(configs);
> ```
> 
> ## Scripts inside package.json
> > In generate have to provide the path otherwise it is creating inside cwd/pwd
> 
> ```json
> {
>     "typeorm": "typeorm-ts-node-commonjs -d ormconfig.ts",
>     "migration:generate": "npm run typeorm migration:generate ./src/modules/database/migrations/$npm_config_name",
> }
> ```
> 
> ## command to run
> ```shell
> npm run migration:generate  --name=InitialMigration
> ```

thank you, this works for me

**Comment by dberardo-com** [comment]
thanks a lot for your comment ... however, this is almost 100% the same command i am using to run the script and i still get that strange error of the reflect-metadata\Reflect.js:354:23 node module ... 

i am thinking this might be due to some dependencies ?? not sure, i am using 

"typeorm": "^0.3.17",
node: 16.14
"typescript": "~5.1.6"
