### ISSUE TITLE
typeorm-ts-node-commonjs doesnt work

### ISSUE THREAD

**Issue by matiasgarcia** [typeorm/typeorm#8824]
## Issue Description

I am trying to run the typeorm cli using typeorm-ts-node-commonjs to generate migrations and it doesn't work.

### Expected Behavior

It should work.

### Actual Behavior

```
mgarcia:~/projects/compliance-backend-api(chore/add-typeorm)$ npm run typeorm

> compliance-backend-api@0.0.1 typeorm
> typeorm-ts-node-commonjs

/usr/bin/env: ‘node --require ts-node/register’: No such file or directory
```

### Steps to Reproduce

```
  "dependencies": {
    "@appsignal/express": "^1.0.23",
    "@appsignal/nodejs": "^2.2.10",
    "cors": "^2.8.5",
    "cross-fetch": "^3.1.5",
    "dotenv": "^10.0.0",
    "envalid": "^7.2.1",
    "express": "^4.17.1",
    "express-async-handler": "^1.1.4",
    "http-terminator": "^3.0.4",
    "pg": "^8.7.3",
    "pino-http": "^5.8.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^5.5.12",
    "typeorm": "^0.3.4",
    "ws": "^3.3.3"
  },
  "devDependencies": {
    "@types/cors": "^2.8.12",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.0.2",
    "@types/node": "^16.10.2",
    "@types/pino-http": "^5.8.0",
    "@types/supertest": "^2.0.11",
    "@types/ws": "^8.2.0",
    "@typescript-eslint/eslint-plugin": "^4.32.0",
    "@typescript-eslint/parser": "^4.32.0",
    "eslint": "^7.32.0",
    "jest": "^27.2.4",
    "jest-websocket-mock": "^2.2.1",
    "mock-socket": "^9.0.5",
    "nodemon": "^2.0.13",typeorm-ts-node-commonjs
    "supertest": "^6.1.6",
    "ts-jest": "^27.0.5",
    "ts-node": "^10.2.1",
    "tsc-watch": "^4.5.0",
    "typescript": "^4.4.3"
  },
  "engines": {
    "node": ">=16.10.0",
    "npm": ">=7.24.0"
  }
```

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "ES6",
      "ES5"
    ],                                                /* Specify a set of bundled library declaration files that describe the target runtime environment. */
    "experimentalDecorators": true,                   /* Enable experimental support for TC39 stage 2 draft decorators. */
    "emitDecoratorMetadata": true,                    /* Emit design-type metadata for decorated declarations in source files. */
    "module": "commonjs",                                /* Specify what module code is generated. */
    "rootDir": "./src",                                  /* Specify the root folder within your source files. */
    "moduleResolution": "node",                          /* Specify how TypeScript looks up a file from a given module specifier. */
    "paths": {
      "*": [
        "./node_modules/*"
      ]
    },
    "sourceMap": true,                                   /* Create source map files for emitted JavaScript files. */
    "outDir": "./dist",                                   /* Specify an output folder for all emitted files. */
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */
    "strict": true,                                      /* Enable all strict type-checking options. */
    "noImplicitAny": true,                               /* Enable error reporting for expressions and declarations with an implied `any` type.. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  },
  "exclude": [
    "spec/**/*.ts",
  ]
}

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | 16.10.0  | 
| Typescript version  | 4.4.3  | 
| TypeORM version     | 0.3.4  |

### Additional Context

I used npx typeorm init in my current project.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by codeninja** [comment]
I have the same issue. typeorm-ts-node-esm is broken in the same way.

**Comment by pleerock** [comment]
adding @giladgd

**Comment by giladgd** [comment]
PR #8821 fixes this, once a new version is released this should be solved

**Comment by matiasgarcia** [comment]
> @matiasgarcia I'm curious what your "typeorm" script looks like in your package.json...if you posted it, I'm not seeing it sorry ;)

I tried everything:

1. "typeorm": "typeorm-ts-node-commonjs",
2. "typeorm": "typeorm",
3. "typeorm": "typeorm-ts-node-esm"

My project compiles to commonjs so I guess the first option is fine but still.

**Comment by matiasgarcia** [comment]
I tried following the guidelines in https://github.com/typeorm/typeorm/blob/master/docs/using-cli.md#if-entities-files-are-in-typescript FYI

**Comment by matiasgarcia** [comment]
> PR #8821 fixes this, once a new version is released this should be solved

Is there any workaround for this in the meantime?

**Comment by msalsbery** [comment]
> > @matiasgarcia I'm curious what your "typeorm" script looks like in your package.json...if you posted it, I'm not seeing it sorry ;)
> 
> I tried everything:
> 
> 1. "typeorm": "typeorm-ts-node-commonjs",
> 2. "typeorm": "typeorm",
> 3. "typeorm": "typeorm-ts-node-esm"
> 
> My project compiles to commonjs so I guess the first option is fine but still.

See #8810  After researching a few issues here I got it working

**Comment by akivajgordon** [comment]
I was on typeorm v0.3.4 with the same issue.

I upgraded to v0.3.6 and the problem went away, thanks to #8821 (fixed in 0.3.5 actually).

**Comment by odusseys** [comment]
no luck for me, tried almost everything ... ESM support is terrible

**Comment by marcel-mintouge** [comment]
@ItsTarik Were you able to fix that?

**Comment by ItsTarik** [comment]
@marcel-mintouge i am done with typeorm for good(issues from 2019 are still present with a new look), I migrated to drizzle-orm 👌 so good luck to everyone !

**Comment by marcel-mintouge** [comment]
It worked for me in the end with `typeorm-ts-node-esm`, I just had some absolute imports that weren't working well with the script, so I made them relative.

`typeorm-ts-node-esm migration:generate -d <path-to-datasource> ...`

**Comment by AndriyCh1** [comment]
I’ve found a solution for handling relative imports ([source](https://stackoverflow.com/questions/76155221/using-typeorm-cli-with-yarn-berry-and-ts-path-aliases/77996086#77996086)). 

You need to add the following to tsconfig.json:

```
{
  "ts-node": {
    "require": [
      "tsconfig-paths/register"
    ]
  },
  "compilerOptions": {
    ...
  }
}
```

Credit: [#1556](https://github.com/typeorm/typeorm/issues/1556#issuecomment-2171431365)

**Comment by aqeelat** [comment]
Would switching from ts-node to jiti be helpful in this scenario? We could also add it as another option (i.e. typeorm-jiti)

**Comment by iago-f-s-e** [comment]
Thanks, @AndriyCh1 It worked for me

**Comment by wicfasho** [comment]
After upgrading to TypeORM 0.3.25, I encountered an issue where migrations were getting stuck during execution. Downgrading to 0.3.20 resolved the problem.

```
"typeorm": "^0.3.20",
"typeorm-ts-node-commonjs": "^0.3.20"
```

If you’re experiencing similar migration issues on 0.3.25, consider using 0.3.20 as a stable fallback.

**Comment by killian-drwell** [comment]
@wicfasho I am experiencing this issue with 0.3.20. Migrations work fine with Postgres, but hang with MySQL and MariaDB. I have since gotten the execution to work by executing with npx: `npx typeorm-ts-node-commonjs migration:run|generate ...`.

**Comment by wicfasho** [comment]
> [@wicfasho](https://github.com/wicfasho) I am experiencing this issue with 0.3.20. Migrations work fine with Postgres, but hang with MySQL and MariaDB. I have since gotten the execution to work by executing with npx: `npx typeorm-ts-node-commonjs migration:run|generate ...`.

What are the versions of your `typeorm` and `typeorm-ts-node-commonjs`?

**Comment by killian-drwell** [comment]
@wicfasho 

typeorm and typeorm-ts-node-commonjs are both `^0.3.20`
