### ISSUE TITLE
Unable to query data where relationship needs to be null using Repository method

### ISSUE THREAD

**Issue by dweinstein1** [typeorm/typeorm#8890]
## Issue Description

When I'm trying to query a model, where I need the relationship to be NULL, the SQL query doesn't add the WHERE IS NULL.

### Expected Behavior

```typescript
const box = await AppDataSource.getRepository(BoxModel).find({
      relations: {
        pallet: true,
      },
      where: {
        pallet: IsNull(),
      },
    });
```
```SQL
SELECT * FROM "boxes" "BoxModel" LEFT JOIN "pallets" "BoxModelBoxModel_pallet" ON "BoxModelBoxModel_pallet"."id"="BoxModel"."pallet_id" AND ("BoxModel_BoxModel_pallet"."deleted_at" IS NULL) WHERE "BoxModel"."deleted_at" IS NULL AND  "BoxModel"."pallet_id" IS NULL;
```
### Actual Behavior

```SQL
SELECT * FROM "boxes" "BoxModel"   LEFT JOIN "pallets" "BoxModelBoxModel_pallet" ON BoxModelBoxModel_pallet"."id"="BoxModel"."pallet_id" AND ("BoxModel_BoxModel_pallet"."deleted_at" IS NULL) WHERE "BoxModel"."deleted_at" IS NULL;
```

### Steps to Reproduce

1. Create a model with a nullable ManyToOne relationship.
2. Try to query from the children model, where the parent relationship is NULL. 

```typescript
@Entity({ name: 'pallets' })
export class PalletModel extends CustomBaseEntity {
  @OneToMany(() => BoxModel, (box) => box.pallet)
  boxes!: BoxModel[];
}

@Entity({ name: 'boxes' })
export class BoxModel extends CustomBaseEntity {
  @ManyToOne(() => PalletModel, (pallet) => pallet.boxes, { nullable: true })
  @JoinColumn({ name: 'pallet_id' })
  pallet?: PalletModel | null;
}
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  MacOS 12.1        |
| Node.js version     | 16.13.2| 
| Typescript version  | 4.5.2  | 
| TypeORM version     | 0.3.5 | 

### Relevant Database Driver(s)

| DB Type           | Reproducible  |
|-------------------| ---           |
| `aurora-mysql`    | yes|
| `aurora-postgres` | yes|
| `better-sqlite3`  | yes|
| `cockroachdb`     | yes|
| `cordova`         | yes|
| `expo`            | yes|
| `mongodb`         | yes|
| `mysql`           | yes|
| `nativescript`    | yes|
| `oracle`          | yes|
| `postgres`        | yes|
| `react-native`    | yes|
| `sap`             | yes|
| `spanner`         | yes|
| `sqlite`          | yes|
| `sqlite-abstract` | yes|
| `sqljs`           | yes|
| `sqlserver`       | yes|

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by florianvandamme** [comment]
I have exactly the same issue. Any fix in the making?

**Comment by justvamp** [comment]
Same here. Version 0.3.6.

@pleerock This is one of many issues of this kind opened here for the last couple of weeks.
At least two others: https://github.com/typeorm/typeorm/issues/8816 and https://github.com/typeorm/typeorm/issues/8945.

The problem is really serious. Looks like typeorm 0.3 is not production-ready yet.

Are there any problems with the reproduce case or something? Do you need any assistance to fix this asap?

**Comment by GM-Alex** [comment]
@pleerock Any estimated for this? It's somehow a critical one and a fix is available by @pixtron. I already tested his PR and works as expected.

**Comment by eduardmarcinco** [comment]
@pleerock is it possible to prioritize this issue? `.find()` is broken for a long time and prevent us using typeorm.

**Comment by pixtron** [comment]
A workaround for this issue that does not require any fix is to specify a `JoinColumn` on the `ManyToOne` side and then query the `JoinColumn` directly.

```ts
@Entity()
export class Author {
    @PrimaryColumn()
    id: number

    @OneToMany(() => Post, (post) => post.author)
    posts: Post[]
}

@Entity()
export class Post {
    @PrimaryGeneratedColumn()
    id: number

    @ManyToOne(() => Author, (author) => author.posts, {
        nullable: true,
    })
    @JoinColumn({name: 'author_id'})
    author: Author | null

    @Column({
        nullable: true,
    })
    author_id: number | null
}

const posts = await dataSource.getRepository(Post)
    .find({
        relations: ['author'],
        where: [
            {
                author_id: In([2, 3]),
            },
            {
                author_id: IsNull(),
            },
        ],
        order: {
            id: 'ASC'
        }
    })
```

**Comment by GM-Alex** [comment]
@pleerock Is there any chance to get this fixed soon? I know it's vacation time but I, and I think many others, would appreciate it.

**Comment by m3c-ode** [comment]
Hi there,

I may say that I'm facing an issue that is really close to this one, but mine still doesn't work, after having upgraded the package's version. 
In a OnetoOne relationship, between 2 repositories: Address and Warehouse, I am trying to fetch all the addresses that do not have a warehouse relation. I have been trying to use Repository manager instead of the QueryBuilder.

These are my models: 

```
@Entity()
export class Address {
	[key: string]: string | string[] | number | Record<string, unknown> | Date;
	@PrimaryGeneratedColumn({
		type: "bigint",
		name: "address_id",
	})
	id: string;

	@Column({
		nullable: true,
	})
	customerId?: string;

	@Field()
	@OneToOne(() => Warehouse, (warehouse: Warehouse) => warehouse.address, { nullable: true })
	warehouse?: string | null;
}

@Entity()
export class Warehouse {
	@PrimaryGeneratedColumn({
		type: "bigint",
	})
	id: string;

	@Field()
	@Column()
	name: string;

	@Field()
	@Column({ nullable: false })
	merchantId: string;

	@OneToOne(() => Address, { eager: true, cascade: true })
	@JoinColumn()
	address: Address;
}

```

Trying this code:

```
    findAllAddresses(@Query() query: any) {
        return this.addressesService.find({
            relations: {
                warehouse: true
            },
            where: {
                warehouse: null
            }
        });
    }
```

Returns all of my results. Even the ones with the `warehouse: null` field.

I found and tried with

```
            where: {
                warehouse: IsNull()
            }
```

But my query actually returns an error (not in TS):

>     This relation isn't supported by given find operator

How can I filter on this field/relation?

**Comment by cognot** [comment]
Hi,

facing the same issue with a ManyToMany relation. I managed to work around the problem using a SelectQueryBuilder, but still it would be nice if it worked with the entity repository approach.

Regards,
Richard.

**Comment by sheikx1221** [comment]
I was stuck with this issue. I had to check a relation exists or not
what I was doing before with Repository API
`await this.messageModel.find({ where: { driver: IsNull() }});`

After looking in the comments for this issue, I lost hope thinking now I have to use QueryBuilder API but this solved my issue
`await this.messageModel.find({ where: { driver: { id: IsNull() }}});`

Try this and I hope your issue will be solved

**Comment by s1njar** [comment]
Hi,

Is there any news on this topic. This is a plausible use case to search for entities that do not have a specific relation!

Kind regards,
s1njar

**Comment by GM-Alex** [comment]
@s1njar The issue is closed and resolved.

**Comment by m3c-ode** [comment]
> @s1njar The issue is closed and resolved.

@GM-Alex Where can we find the solution?

**Comment by GM-Alex** [comment]
@m3c-ode Just use the latest version of typeorm.

**Comment by conradkirschner** [comment]
@GM-Alex  Seems like this issue is still there, facing it when I want to do search if the relation is Null or has a specific value

```
await this.tourRepository.findOne({
      relations: [ 'relation'],
      where: [
        {
          id: id,
          relation: {
            someValue,
          },
        },
        {
          id: id,
          tourInstruction: IsNull(),
        },
      ],
    });
  }
```

**Comment by growms** [comment]
On 0.3.16 i still have the problem with a OneToOne. @GM-Alex Do you talk about the 0.4 alpha ?

**Comment by GM-Alex** [comment]
@growms 0.3.x fixed it for me.

**Comment by MatheusLeitao** [comment]
I've solved it with the reverse column `IsNull()` instead of it's object.

```typescript

const box = await AppDataSource.getRepository(BoxModel).find({
      relations: {
        pallet: true,
      },
      where: {
        pallet: {
           box_id: IsNull();
          }      
        },
    });

```

**Comment by diorgeneseugenio** [comment]
> I've solved it with the reverse column `IsNull()` instead of it's object.
> 
> ```ts
> const box = await AppDataSource.getRepository(BoxModel).find({
>       relations: {
>         pallet: true,
>       },
>       where: {
>         pallet: {
>            box_id: IsNull();
>           }      
>         },
>     });
> ```

Love you man 🫶

**Comment by dawidpstrak** [comment]
Using `IsNull()` instead of `null` working for me.
```
where: { id, replies: { parent: IsNull() } }
```

**Comment by joshclement0** [comment]
Can also be solved by using querybuilder
```
const box = await AppDataSource.getRepository(BoxModel)
   .createQuerybuilder('boxModel')
   .leftJoinAndSelect('boxModel.pallet','pallet','pallet.id=boxModel.pallet_id AND pallet.box_model_id IS NOT NULL')
   .getMany()
```
might be nice to add this functionality to FindOptions.relations
